class_name RadixConstants

const SOUND_ROCKET_START = preload("res://assets/sound_effects/rocket1_start.mp3")
const SOUND_ROCKET_END = preload("res://assets/sound_effects/rocket1_end.mp3")

const STRUCTURES = {
	Enums.SceneId.RADIX_HEART:
	{
		"scene": "res://source/factions/the_radix/structures/Heart.tscn",
		"unit_name": "Heart",
		"description": "Central command hub. Builds structures and defences",
		"faction": Enums.Faction.RADIX,
		"production_tab_type": Enums.ProductionTabType.STRUCTURE,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F1,
		"produces":
		[
			Enums.ProductionTabType.STRUCTURE,
			Enums.ProductionTabType.DEFENCES,
			Enums.ProductionTabType.INFANTRY,
		],
		"max_concurrent_structures": 99,
		"sight_range": 10.0,
		"hp": 20,
		"hp_max": 20,
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.5,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.75,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.5,
			Enums.DamageTypes.MELEE: 0.75,
			Enums.DamageTypes.PLASMA: 0.25,
			Enums.DamageTypes.PRISM: 0.5,
			Enums.DamageTypes.RIFLE: 0.75,
			Enums.DamageTypes.ROCKET: 0.25,
			Enums.DamageTypes.TESLA: 0.25,
		},
		"spreads_vines": true,
		"costs": {"credits": 8},
		"build_time": 10.0,
	},
	Enums.SceneId.RADIX_SPIRE:
	{
		"scene": "res://source/factions/the_radix/structures/Spire.tscn",
		"unit_name": "Spire",
		"description": "Tier 1 infantry nursery seeded into place by a Seedling.",
		"faction": Enums.Faction.RADIX,
		"production_tab_type": Enums.ProductionTabType.STRUCTURE,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F2,
		"produces": [Enums.ProductionTabType.INFANTRY],
		"requires_seedling_to_start": true,
		"sight_range": 8.0,
		"hp": 12,
		"hp_max": 12,
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.0,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.25,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.0,
			Enums.DamageTypes.MELEE: 0.25,
			Enums.DamageTypes.PLASMA: 0.0,
			Enums.DamageTypes.PRISM: 0.0,
			Enums.DamageTypes.RIFLE: 0.25,
			Enums.DamageTypes.ROCKET: 0.0,
			Enums.DamageTypes.TESLA: 0.0,
		},
		"costs": {"credits": 600},
		"build_time": 6.0,
	},
	Enums.SceneId.RADIX_THORN_FORGE:
	{
		"scene": "res://source/factions/the_radix/structures/ThornForge.tscn",
		"unit_name": "Thorn Forge",
		"description": "Tier 1 vehicle foundry seeded into place by a Seedling.",
		"faction": Enums.Faction.RADIX,
		"production_tab_type": Enums.ProductionTabType.STRUCTURE,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F3,
		"produces": [Enums.ProductionTabType.VEHICLE],
		"requires_seedling_to_start": true,
		"sight_range": 8.0,
		"hp": 18,
		"hp_max": 18,
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.25,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.35,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.15,
			Enums.DamageTypes.MELEE: 0.25,
			Enums.DamageTypes.PLASMA: 0.15,
			Enums.DamageTypes.PRISM: 0.15,
			Enums.DamageTypes.RIFLE: 0.35,
			Enums.DamageTypes.ROCKET: 0.15,
			Enums.DamageTypes.TESLA: 0.15,
		},
		"costs": {"credits": 2000},
		"build_time": 20.0,
	},
	Enums.SceneId.RADIX_SKY_BLOOM:
	{
		"scene": "res://source/factions/the_radix/structures/SkyBloom.tscn",
		"unit_name": "Sky Bloom",
		"description": "Tier 1 aerial cradle seeded into place by a Seedling.",
		"faction": Enums.Faction.RADIX,
		"production_tab_type": Enums.ProductionTabType.STRUCTURE,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F4,
		"produces": [Enums.ProductionTabType.AIR],
		"requires_seedling_to_start": true,
		"sight_range": 8.0,
		"hp": 16,
		"hp_max": 16,
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.15,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.25,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.15,
			Enums.DamageTypes.MELEE: 0.25,
			Enums.DamageTypes.PLASMA: 0.15,
			Enums.DamageTypes.PRISM: 0.15,
			Enums.DamageTypes.RIFLE: 0.25,
			Enums.DamageTypes.ROCKET: 0.15,
			Enums.DamageTypes.TESLA: 0.15,
		},
		"costs": {"credits": 2000},
		"build_time": 20.0,
	},
	Enums.SceneId.RADIX_LINKER:
	{
		"scene": "res://source/factions/the_radix/structures/Linker.tscn",
		"unit_name": "Linker",
		"description":
		"Passive bio-link structure that siphons income from nearby resource tiles without consuming them.",
		"faction": Enums.Faction.RADIX,
		"production_tab_type": Enums.ProductionTabType.STRUCTURE,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F5,
		"requires_seedling_to_start": true,
		"sight_range": 8.0,
		"hp": 14,
		"hp_max": 14,
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.1,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.25,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.1,
			Enums.DamageTypes.MELEE: 0.25,
			Enums.DamageTypes.PLASMA: 0.1,
			Enums.DamageTypes.PRISM: 0.1,
			Enums.DamageTypes.RIFLE: 0.25,
			Enums.DamageTypes.ROCKET: 0.1,
			Enums.DamageTypes.TESLA: 0.1,
		},
		"costs": {"credits": 900},
		"build_time": 10.0,
	},
	Enums.SceneId.RADIX_SAPLING:
	{
		"scene": "res://source/factions/the_radix/structures/Sapling.tscn",
		"unit_name": "Sapling",
		"description":
		"Rooted Seedling. Spreads creep in a small radius. Created by the Seedling 'spread' ability.",
		"faction": Enums.Faction.RADIX,
		# Sapling is not produced via a production tab; it is spawned by the spread ability.
		"sight_range": 5.0,
		"hp": 40,
		"hp_max": 40,
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.0,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.1,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.0,
			Enums.DamageTypes.MELEE: 0.1,
			Enums.DamageTypes.PLASMA: 0.0,
			Enums.DamageTypes.PRISM: 0.0,
			Enums.DamageTypes.RIFLE: 0.1,
			Enums.DamageTypes.ROCKET: 0.0,
			Enums.DamageTypes.TESLA: 0.0,
		},
		"costs": {"credits": 0},
		"build_time": 0.5,
	},
	Enums.SceneId.RADIX_CORE:
	{
		"scene": "res://source/factions/the_radix/structures/Core.tscn",
		"unit_name": "Core",
		"description": "Secondary Rootmind node. Forward expansion anchor for connected growth.",
		"faction": Enums.Faction.RADIX,
		"production_tab_type": Enums.ProductionTabType.STRUCTURE,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F6,
		"requires_seedling_to_start": true,
		"sight_range": 9.0,
		"hp": 16,
		"hp_max": 16,
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.4,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.5,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.4,
			Enums.DamageTypes.MELEE: 0.5,
			Enums.DamageTypes.PLASMA: 0.2,
			Enums.DamageTypes.PRISM: 0.4,
			Enums.DamageTypes.RIFLE: 0.5,
			Enums.DamageTypes.ROCKET: 0.2,
			Enums.DamageTypes.TESLA: 0.2,
		},
		"spreads_vines": true,
		"costs": {"credits": 1500},
		"build_time": 18.0,
	},
	Enums.SceneId.RADIX_SYNAPSE_GROVE:
	{
		"scene": "res://source/factions/the_radix/structures/SynapseGrove.tscn",
		"unit_name": "Synapse Grove",
		"description": "Tier 2 tech grove. Provides upgrades and base detection on owned creep.",
		"faction": Enums.Faction.RADIX,
		"production_tab_type": Enums.ProductionTabType.STRUCTURE,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F7,
		"requires_seedling_to_start": true,
		"sight_range": 12.0,
		"hp": 14,
		"hp_max": 14,
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.1,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.25,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.1,
			Enums.DamageTypes.MELEE: 0.25,
			Enums.DamageTypes.PLASMA: 0.1,
			Enums.DamageTypes.PRISM: 0.1,
			Enums.DamageTypes.RIFLE: 0.25,
			Enums.DamageTypes.ROCKET: 0.1,
			Enums.DamageTypes.TESLA: 0.1,
		},
		"costs": {"credits": 1200},
		"build_time": 16.0,
	},
	Enums.SceneId.RADIX_ROOT_GATE:
	{
		"scene": "res://source/factions/the_radix/structures/RootGate.tscn",
		"unit_name": "Root Gate",
		"description": "Paired creep-linked teleport portal for tactical mobility.",
		"faction": Enums.Faction.RADIX,
		"production_tab_type": Enums.ProductionTabType.STRUCTURE,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F8,
		"requires_seedling_to_start": true,
		"sight_range": 6.0,
		"hp": 12,
		"hp_max": 12,
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.1,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.2,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.1,
			Enums.DamageTypes.MELEE: 0.2,
			Enums.DamageTypes.PLASMA: 0.1,
			Enums.DamageTypes.PRISM: 0.1,
			Enums.DamageTypes.RIFLE: 0.2,
			Enums.DamageTypes.ROCKET: 0.1,
			Enums.DamageTypes.TESLA: 0.1,
		},
		"costs": {"credits": 800},
		"build_time": 12.0,
	},
}

const DEFENCES = {
	Enums.SceneId.RADIX_WALL:
	{
		"scene": "res://source/factions/the_radix/structures/Wall.tscn",
		"unit_name": "Living Wall",
		"description": "Organic blocker segment. Shapes paths and chokes on owned creep.",
		"faction": Enums.Faction.RADIX,
		"production_tab_type": Enums.ProductionTabType.DEFENCES,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F1,
		"requires_seedling_to_start": true,
		"sight_range": 4.0,
		"hp": 12,
		"hp_max": 12,
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.5,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.5,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.5,
			Enums.DamageTypes.MELEE: 0.75,
			Enums.DamageTypes.PLASMA: 0.25,
			Enums.DamageTypes.PRISM: 0.25,
			Enums.DamageTypes.RIFLE: 0.75,
			Enums.DamageTypes.ROCKET: 0.25,
			Enums.DamageTypes.TESLA: 0.25,
		},
		"costs": {"credits": 100},
		"build_time": 6.0,
	},
	Enums.SceneId.RADIX_ACID_SPEWER:
	{
		"scene": "res://source/factions/the_radix/structures/AcidSpewer.tscn",
		"unit_name": "Acid Spewer",
		"description": "Anti-infantry corrosive defence. Tears light ground at short range.",
		"faction": Enums.Faction.RADIX,
		"production_tab_type": Enums.ProductionTabType.DEFENCES,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F2,
		"requires_seedling_to_start": true,
		"sight_range": 8.0,
		"hp": 14,
		"hp_max": 14,
		"attack_damage": 10,
		"attack_type": "corrosive",
		"attack_interval": 0.6,
		"attack_range": 5.0,
		"can_attack_vines": true,
		"projectile_type": Enums.Projectile.BULLETS,
		"attack_domains":
		[
			Enums.MovementTypes.LAND,
		],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.25,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.25,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.25,
			Enums.DamageTypes.MELEE: 0.5,
			Enums.DamageTypes.PLASMA: 0.1,
			Enums.DamageTypes.PRISM: 0.1,
			Enums.DamageTypes.RIFLE: 0.5,
			Enums.DamageTypes.ROCKET: 0.1,
			Enums.DamageTypes.TESLA: 0.1,
		},
		"costs": {"credits": 400},
		"build_time": 10.0,
	},
	Enums.SceneId.RADIX_ROOT_IMPALER:
	{
		"scene": "res://source/factions/the_radix/structures/RootImpaler.tscn",
		"unit_name": "Root Impaler",
		"description": "Anti-vehicle defence. Slow-firing piercing roots vs armor.",
		"faction": Enums.Faction.RADIX,
		"production_tab_type": Enums.ProductionTabType.DEFENCES,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F3,
		"requires_seedling_to_start": true,
		"sight_range": 9.0,
		"hp": 18,
		"hp_max": 18,
		"attack_damage": 35,
		"attack_type": "melee",
		"attack_interval": 1.6,
		"attack_range": 6.5,
		"can_attack_vines": true,
		"attack_domains":
		[
			Enums.MovementTypes.LAND,
		],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.5,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.5,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.5,
			Enums.DamageTypes.MELEE: 0.5,
			Enums.DamageTypes.PLASMA: 0.25,
			Enums.DamageTypes.PRISM: 0.25,
			Enums.DamageTypes.RIFLE: 0.5,
			Enums.DamageTypes.ROCKET: 0.25,
			Enums.DamageTypes.TESLA: 0.25,
		},
		"costs": {"credits": 600},
		"build_time": 12.0,
	},
	Enums.SceneId.RADIX_SPORE_CROWN:
	{
		"scene": "res://source/factions/the_radix/structures/SporeCrown.tscn",
		"unit_name": "Spore Crown",
		"description": "Anti-air defence. Rapid spore bursts vs aircraft over groves.",
		"faction": Enums.Faction.RADIX,
		"production_tab_type": Enums.ProductionTabType.DEFENCES,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F4,
		"requires_seedling_to_start": true,
		"sight_range": 9.0,
		"hp": 14,
		"hp_max": 14,
		"attack_damage": 12,
		"attack_type": "corrosive",
		"attack_interval": 0.5,
		"attack_range": 7.0,
		"can_attack_vines": false,
		"projectile_type": Enums.Projectile.BULLETS,
		"attack_domains":
		[
			Enums.MovementTypes.AIR,
		],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.25,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.25,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.25,
			Enums.DamageTypes.MELEE: 0.25,
			Enums.DamageTypes.PLASMA: 0.1,
			Enums.DamageTypes.PRISM: 0.1,
			Enums.DamageTypes.RIFLE: 0.25,
			Enums.DamageTypes.ROCKET: 0.1,
			Enums.DamageTypes.TESLA: 0.1,
		},
		"costs": {"credits": 500},
		"build_time": 11.0,
	},
	Enums.SceneId.RADIX_SYNAPSE_WATCHER:
	{
		"scene": "res://source/factions/the_radix/structures/SynapseWatcher.tscn",
		"unit_name": "Synapse Watcher",
		"description":
		"Static detector. Reveals stealth, burrowed, and hidden threats on owned growth.",
		"faction": Enums.Faction.RADIX,
		"production_tab_type": Enums.ProductionTabType.DEFENCES,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F5,
		"requires_seedling_to_start": true,
		"sight_range": 12.0,
		"hp": 12,
		"hp_max": 12,
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.1,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.2,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.1,
			Enums.DamageTypes.MELEE: 0.2,
			Enums.DamageTypes.PLASMA: 0.1,
			Enums.DamageTypes.PRISM: 0.1,
			Enums.DamageTypes.RIFLE: 0.2,
			Enums.DamageTypes.ROCKET: 0.1,
			Enums.DamageTypes.TESLA: 0.1,
		},
		"costs": {"credits": 400},
		"build_time": 9.0,
	},
	Enums.SceneId.RADIX_MENDING_FLOWER:
	{
		"scene": "res://source/factions/the_radix/structures/MendingFlower.tscn",
		"unit_name": "Mending Flower",
		"description": "Heals nearby Radix units and living structures over time.",
		"faction": Enums.Faction.RADIX,
		"production_tab_type": Enums.ProductionTabType.DEFENCES,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F6,
		"requires_seedling_to_start": true,
		"sight_range": 6.0,
		"hp": 12,
		"hp_max": 12,
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.1,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.2,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.1,
			Enums.DamageTypes.MELEE: 0.2,
			Enums.DamageTypes.PLASMA: 0.1,
			Enums.DamageTypes.PRISM: 0.1,
			Enums.DamageTypes.RIFLE: 0.2,
			Enums.DamageTypes.ROCKET: 0.1,
			Enums.DamageTypes.TESLA: 0.1,
		},
		"costs": {"credits": 450},
		"build_time": 10.0,
	},
}

const INFANTRY = {
	Enums.SceneId.RADIX_SEEDLING:
	{
		"scene": "res://source/factions/the_radix/units/Seedling.tscn",
		"unit_name": "Seedling",
		"description":
		"A fragile sprout creature. Unarmed support unit for scouting, creep spread, and construction.",
		"faction": Enums.Faction.RADIX,
		"production_tab_type": Enums.ProductionTabType.INFANTRY,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F1,
		"sight_range": 6.0,
		"hp": 80,
		"hp_max": 80,
		"can_move_through_vines": true,
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.0,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.0,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.0,
			Enums.DamageTypes.MELEE: 0.0,
			Enums.DamageTypes.PLASMA: 0.0,
			Enums.DamageTypes.PRISM: 0.0,
			Enums.DamageTypes.RIFLE: 0.0,
			Enums.DamageTypes.ROCKET: 0.0,
			Enums.DamageTypes.TESLA: 0.0,
		},
		"costs": {"credits": 1},
		"build_time": 2.5,
	},
	Enums.SceneId.RADIX_SNAPLING:
	{
		"scene": "res://source/factions/the_radix/units/Snapling.tscn",
		"unit_name": "Snapling",
		"description": "Fast, low-cost melee unit. Rushes enemies and bites.",
		"faction": Enums.Faction.RADIX,
		"production_tab_type": Enums.ProductionTabType.INFANTRY,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F2,
		"sight_range": 5.0,
		"hp": 60,
		"hp_max": 60,
		"attack_damage": 8,
		"attack_interval": 1.2,
		"attack_range": 0.5,
		"attack_type": "melee",
		"attack_domains": [Enums.MovementTypes.LAND],
		"movement_domains": [Enums.MovementTypes.LAND],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.0,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.0,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.0,
			Enums.DamageTypes.MELEE: 0.0,
			Enums.DamageTypes.PLASMA: 0.0,
			Enums.DamageTypes.PRISM: 0.0,
			Enums.DamageTypes.RIFLE: 0.0,
			Enums.DamageTypes.ROCKET: 0.0,
			Enums.DamageTypes.TESLA: 0.0,
		},
		"costs": {"credits": 80},
		"build_time": 8.0,
	},
	Enums.SceneId.RADIX_TREANT:
	{
		"scene": "res://source/factions/the_radix/units/Treant.tscn",
		"unit_name": "Treant",
		"description": "Ranged humanoid plant. Attacks ground and air with thorn projectiles.",
		"faction": Enums.Faction.RADIX,
		"production_tab_type": Enums.ProductionTabType.INFANTRY,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F3,
		"sight_range": 7.0,
		"hp": 120,
		"hp_max": 120,
		"attack_damage": 12,
		"attack_interval": 1.8,
		"attack_range": 5.0,
		"attack_type": "ranged",
		"attack_domains": [Enums.MovementTypes.LAND, Enums.MovementTypes.AIR],
		"movement_domains": [Enums.MovementTypes.LAND],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.0,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.1,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.0,
			Enums.DamageTypes.MELEE: 0.1,
			Enums.DamageTypes.PLASMA: 0.0,
			Enums.DamageTypes.PRISM: 0.0,
			Enums.DamageTypes.RIFLE: 0.0,
			Enums.DamageTypes.ROCKET: 0.0,
			Enums.DamageTypes.TESLA: 0.0,
		},
		"costs": {"credits": 160},
		"build_time": 14.0,
	},
	Enums.SceneId.RADIX_INTEGRATOR:
	{
		"scene": "res://source/factions/the_radix/units/Integrator.tscn",
		"unit_name": "Integrator",
		"description": "Faction engineer. Infests neutral or enemy structures to take control.",
		"faction": Enums.Faction.RADIX,
		"production_tab_type": Enums.ProductionTabType.INFANTRY,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F4,
		"sight_range": 7.0,
		"hp": 100,
		"hp_max": 100,
		"can_move_through_vines": true,
		"movement_domains": [Enums.MovementTypes.LAND],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.0,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.0,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.0,
			Enums.DamageTypes.MELEE: 0.0,
			Enums.DamageTypes.PLASMA: 0.0,
			Enums.DamageTypes.PRISM: 0.0,
			Enums.DamageTypes.RIFLE: 0.0,
			Enums.DamageTypes.ROCKET: 0.0,
			Enums.DamageTypes.TESLA: 0.0,
		},
		"costs": {"credits": 130},
		"build_time": 11.0,
	},
	Enums.SceneId.RADIX_LASHGUARD:
	{
		"scene": "res://source/factions/the_radix/units/Lashguard.tscn",
		"unit_name": "Lashguard",
		"description": "Slow durable melee frontline. Tougher when fighting on owned creep.",
		"faction": Enums.Faction.RADIX,
		"production_tab_type": Enums.ProductionTabType.INFANTRY,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F5,
		"sight_range": 5.0,
		"hp": 220,
		"hp_max": 220,
		"can_move_through_vines": true,
		"attack_damage": 18,
		"attack_type": "melee",
		"attack_interval": 1.0,
		"attack_range": 1.4,
		"attack_domains": [Enums.MovementTypes.LAND],
		"movement_domains": [Enums.MovementTypes.LAND],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.25,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.25,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.25,
			Enums.DamageTypes.MELEE: 0.5,
			Enums.DamageTypes.PLASMA: 0.1,
			Enums.DamageTypes.PRISM: 0.1,
			Enums.DamageTypes.RIFLE: 0.5,
			Enums.DamageTypes.ROCKET: 0.1,
			Enums.DamageTypes.TESLA: 0.1,
		},
		"costs": {"credits": 180},
		"build_time": 14.0,
	},
	Enums.SceneId.RADIX_SPORECASTER:
	{
		"scene": "res://source/factions/the_radix/units/Sporecaster.tscn",
		"unit_name": "Sporecaster",
		"description": "AoE anti-infantry zone-denial. Slow projectile, telegraphed splash.",
		"faction": Enums.Faction.RADIX,
		"production_tab_type": Enums.ProductionTabType.INFANTRY,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F6,
		"sight_range": 7.0,
		"hp": 110,
		"hp_max": 110,
		"can_move_through_vines": true,
		"attack_damage": 22,
		"attack_type": "corrosive",
		"attack_interval": 1.8,
		"attack_range": 5.5,
		"projectile_type": Enums.Projectile.BULLETS,
		"attack_domains": [Enums.MovementTypes.LAND],
		"movement_domains": [Enums.MovementTypes.LAND],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.0,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.0,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.0,
			Enums.DamageTypes.MELEE: 0.0,
			Enums.DamageTypes.PLASMA: 0.0,
			Enums.DamageTypes.PRISM: 0.0,
			Enums.DamageTypes.RIFLE: 0.0,
			Enums.DamageTypes.ROCKET: 0.0,
			Enums.DamageTypes.TESLA: 0.0,
		},
		"costs": {"credits": 200},
		"build_time": 14.0,
	},
	Enums.SceneId.RADIX_BLOOMKEEPER:
	{
		"scene": "res://source/factions/the_radix/units/Bloomkeeper.tscn",
		"unit_name": "Bloomkeeper",
		"description": "Mobile regen support. Heals nearby living units; high-value target.",
		"faction": Enums.Faction.RADIX,
		"production_tab_type": Enums.ProductionTabType.INFANTRY,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F7,
		"sight_range": 8.0,
		"hp": 120,
		"hp_max": 120,
		"can_move_through_vines": true,
		"movement_domains": [Enums.MovementTypes.LAND],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.0,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.0,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.0,
			Enums.DamageTypes.MELEE: 0.0,
			Enums.DamageTypes.PLASMA: 0.0,
			Enums.DamageTypes.PRISM: 0.0,
			Enums.DamageTypes.RIFLE: 0.0,
			Enums.DamageTypes.ROCKET: 0.0,
			Enums.DamageTypes.TESLA: 0.0,
		},
		"costs": {"credits": 220},
		"build_time": 14.0,
	},
	Enums.SceneId.RADIX_GAYA:
	{
		"scene": "res://source/factions/the_radix/units/Gaya.tscn",
		"unit_name": "Gaya",
		"description": "T3 fragile caster. Single-target lockdown via root/entangle.",
		"faction": Enums.Faction.RADIX,
		"production_tab_type": Enums.ProductionTabType.INFANTRY,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F8,
		"sight_range": 9.0,
		"hp": 140,
		"hp_max": 140,
		"can_move_through_vines": true,
		"attack_damage": 8,
		"attack_type": "corrosive",
		"attack_interval": 1.4,
		"attack_range": 6.0,
		"projectile_type": Enums.Projectile.BULLETS,
		"attack_domains": [Enums.MovementTypes.LAND, Enums.MovementTypes.AIR],
		"movement_domains": [Enums.MovementTypes.LAND],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.0,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.0,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.0,
			Enums.DamageTypes.MELEE: 0.0,
			Enums.DamageTypes.PLASMA: 0.0,
			Enums.DamageTypes.PRISM: 0.0,
			Enums.DamageTypes.RIFLE: 0.0,
			Enums.DamageTypes.ROCKET: 0.0,
			Enums.DamageTypes.TESLA: 0.0,
		},
		"costs": {"credits": 320},
		"build_time": 18.0,
	},
}

const VEHICLES = {
	Enums.SceneId.RADIX_PROTECTOR:
	{
		"scene": "res://source/factions/the_radix/units/Protector.tscn",
		"unit_name": "Protector",
		"description": "Heavy melee tank-organism. Can absorb damage from nearby allies.",
		"faction": Enums.Faction.RADIX,
		"production_tab_type": Enums.ProductionTabType.VEHICLE,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F1,
		"sight_range": 7.0,
		"hp": 500,
		"hp_max": 500,
		"attack_damage": 25,
		"attack_type": "melee",
		"attack_interval": 1.0,
		"attack_range": 1.6,
		"can_attack_vines": true,
		"attack_domains": [Enums.MovementTypes.LAND],
		"movement_domains": [Enums.MovementTypes.LAND],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.5,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.5,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.5,
			Enums.DamageTypes.MELEE: 0.5,
			Enums.DamageTypes.PLASMA: 0.25,
			Enums.DamageTypes.PRISM: 0.25,
			Enums.DamageTypes.RIFLE: 0.5,
			Enums.DamageTypes.ROCKET: 0.25,
			Enums.DamageTypes.TESLA: 0.25,
		},
		"costs": {"credits": 350},
		"build_time": 16.0,
	},
	Enums.SceneId.RADIX_THORNBACK:
	{
		"scene": "res://source/factions/the_radix/units/Thornback.tscn",
		"unit_name": "Thornback",
		"description": "Anti-armor projectile beast. Pierces vehicles with thorn volleys.",
		"faction": Enums.Faction.RADIX,
		"production_tab_type": Enums.ProductionTabType.VEHICLE,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F2,
		"sight_range": 8.0,
		"hp": 380,
		"hp_max": 380,
		"attack_damage": 38,
		"attack_type": "ranged",
		"attack_interval": 1.6,
		"attack_range": 6.0,
		"can_attack_vines": true,
		"projectile_type": Enums.Projectile.BULLETS,
		"attack_domains": [Enums.MovementTypes.LAND],
		"movement_domains": [Enums.MovementTypes.LAND],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.25,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.25,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.25,
			Enums.DamageTypes.MELEE: 0.5,
			Enums.DamageTypes.PLASMA: 0.1,
			Enums.DamageTypes.PRISM: 0.1,
			Enums.DamageTypes.RIFLE: 0.25,
			Enums.DamageTypes.ROCKET: 0.1,
			Enums.DamageTypes.TESLA: 0.1,
		},
		"costs": {"credits": 320},
		"build_time": 16.0,
	},
	Enums.SceneId.RADIX_BURROWER:
	{
		"scene": "res://source/factions/the_radix/units/Burrower.tscn",
		"unit_name": "Burrower",
		"description": "Ambush vehicle. Burrows to surprise objectives and breach siege lines.",
		"faction": Enums.Faction.RADIX,
		"production_tab_type": Enums.ProductionTabType.VEHICLE,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F3,
		"sight_range": 7.0,
		"hp": 320,
		"hp_max": 320,
		"attack_damage": 28,
		"attack_type": "melee",
		"attack_interval": 1.2,
		"attack_range": 1.6,
		"can_attack_vines": true,
		"attack_domains": [Enums.MovementTypes.LAND],
		"movement_domains": [Enums.MovementTypes.LAND],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.25,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.25,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.25,
			Enums.DamageTypes.MELEE: 0.5,
			Enums.DamageTypes.PLASMA: 0.1,
			Enums.DamageTypes.PRISM: 0.1,
			Enums.DamageTypes.RIFLE: 0.5,
			Enums.DamageTypes.ROCKET: 0.1,
			Enums.DamageTypes.TESLA: 0.1,
		},
		"costs": {"credits": 350},
		"build_time": 18.0,
	},
	Enums.SceneId.RADIX_CARETAKER:
	{
		"scene": "res://source/factions/the_radix/units/Caretaker.tscn",
		"unit_name": "Caretaker",
		"description": "Vehicle support. Heals nearby Radix units by sacrificing own HP.",
		"faction": Enums.Faction.RADIX,
		"production_tab_type": Enums.ProductionTabType.VEHICLE,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F4,
		"sight_range": 7.0,
		"hp": 350,
		"hp_max": 350,
		"movement_domains": [Enums.MovementTypes.LAND],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.1,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.25,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.1,
			Enums.DamageTypes.MELEE: 0.25,
			Enums.DamageTypes.PLASMA: 0.1,
			Enums.DamageTypes.PRISM: 0.1,
			Enums.DamageTypes.RIFLE: 0.25,
			Enums.DamageTypes.ROCKET: 0.1,
			Enums.DamageTypes.TESLA: 0.1,
		},
		"costs": {"credits": 380},
		"build_time": 18.0,
	},
	Enums.SceneId.RADIX_SPEWER:
	{
		"scene": "res://source/factions/the_radix/units/Spewer.tscn",
		"unit_name": "Spewer",
		"description": "Long-range siege from creep. Lobs corrosive splash vs static defences.",
		"faction": Enums.Faction.RADIX,
		"production_tab_type": Enums.ProductionTabType.VEHICLE,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F5,
		"sight_range": 9.0,
		"hp": 420,
		"hp_max": 420,
		"attack_damage": 55,
		"attack_type": "corrosive",
		"attack_interval": 2.4,
		"attack_range": 9.0,
		"can_attack_vines": true,
		"projectile_type": Enums.Projectile.ROCKET,
		"projectile_config":
		{
			"sound_start": SOUND_ROCKET_START,
			"sound_end": SOUND_ROCKET_END,
		},
		"attack_domains": [Enums.MovementTypes.LAND],
		"movement_domains": [Enums.MovementTypes.LAND],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.25,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.25,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.25,
			Enums.DamageTypes.MELEE: 0.25,
			Enums.DamageTypes.PLASMA: 0.1,
			Enums.DamageTypes.PRISM: 0.1,
			Enums.DamageTypes.RIFLE: 0.25,
			Enums.DamageTypes.ROCKET: 0.1,
			Enums.DamageTypes.TESLA: 0.1,
		},
		"costs": {"credits": 600},
		"build_time": 22.0,
	},
	Enums.SceneId.RADIX_YGGDRASIL:
	{
		"scene": "res://source/factions/the_radix/units/Yggdrasil.tscn",
		"unit_name": "Yggdrasil",
		"description": "T3 capital land beast. Heavy ancient-grove protector with regen aura.",
		"faction": Enums.Faction.RADIX,
		"production_tab_type": Enums.ProductionTabType.VEHICLE,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F6,
		"sight_range": 10.0,
		"hp": 1100,
		"hp_max": 1100,
		"attack_damage": 55,
		"attack_type": "melee",
		"attack_interval": 1.4,
		"attack_range": 2.5,
		"can_attack_vines": true,
		"attack_domains": [Enums.MovementTypes.LAND],
		"movement_domains": [Enums.MovementTypes.LAND],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.5,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.5,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.5,
			Enums.DamageTypes.MELEE: 0.75,
			Enums.DamageTypes.PLASMA: 0.25,
			Enums.DamageTypes.PRISM: 0.25,
			Enums.DamageTypes.RIFLE: 0.75,
			Enums.DamageTypes.ROCKET: 0.25,
			Enums.DamageTypes.TESLA: 0.25,
		},
		"costs": {"credits": 1100},
		"build_time": 30.0,
	},
}

const AIR = {
	Enums.SceneId.RADIX_WASP_CLOUD:
	{
		"scene": "res://source/factions/the_radix/units/WaspCloud.tscn",
		"unit_name": "Wasp Cloud",
		"description": "Fragile swarm air harasser. Strong vs exposed workers and convoys.",
		"faction": Enums.Faction.RADIX,
		"production_tab_type": Enums.ProductionTabType.AIR,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F1,
		"sight_range": 8.0,
		"hp": 220,
		"hp_max": 220,
		"movement_domains": [Enums.MovementTypes.AIR],
		"attack_damage": 6,
		"attack_type": "melee",
		"attack_interval": 0.4,
		"attack_range": 1.4,
		"attack_domains": [Enums.MovementTypes.LAND],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.0,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.0,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.0,
			Enums.DamageTypes.MELEE: 0.0,
			Enums.DamageTypes.PLASMA: 0.0,
			Enums.DamageTypes.PRISM: 0.0,
			Enums.DamageTypes.RIFLE: 0.0,
			Enums.DamageTypes.ROCKET: 0.0,
			Enums.DamageTypes.TESLA: 0.0,
		},
		"costs": {"credits": 220},
		"build_time": 14.0,
	},
	Enums.SceneId.RADIX_SPORE_RAY:
	{
		"scene": "res://source/factions/the_radix/units/SporeRay.tscn",
		"unit_name": "Spore Ray",
		"description": "Anti-air specialist. Burst spore volleys vs aircraft and gunships.",
		"faction": Enums.Faction.RADIX,
		"production_tab_type": Enums.ProductionTabType.AIR,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F2,
		"sight_range": 9.0,
		"hp": 360,
		"hp_max": 360,
		"movement_domains": [Enums.MovementTypes.AIR],
		"attack_damage": 24,
		"attack_type": "corrosive",
		"attack_interval": 0.7,
		"attack_range": 6.0,
		"projectile_type": Enums.Projectile.BULLETS,
		"attack_domains": [Enums.MovementTypes.AIR],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.0,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.0,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.0,
			Enums.DamageTypes.MELEE: 0.0,
			Enums.DamageTypes.PLASMA: 0.0,
			Enums.DamageTypes.PRISM: 0.0,
			Enums.DamageTypes.RIFLE: 0.0,
			Enums.DamageTypes.ROCKET: 0.0,
			Enums.DamageTypes.TESLA: 0.0,
		},
		"costs": {"credits": 420},
		"build_time": 18.0,
	},
	Enums.SceneId.RADIX_SKY_LEVIATHAN:
	{
		"scene": "res://source/factions/the_radix/units/SkyLeviathan.tscn",
		"unit_name": "Sky Leviathan",
		"description": "T3 capital air organism. Massive HP, slow, multi-strafe.",
		"faction": Enums.Faction.RADIX,
		"production_tab_type": Enums.ProductionTabType.AIR,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F3,
		"sight_range": 12.0,
		"hp": 900,
		"hp_max": 900,
		"movement_domains": [Enums.MovementTypes.AIR],
		"attack_damage": 60,
		"attack_type": "corrosive",
		"attack_interval": 1.5,
		"attack_range": 8.0,
		"can_attack_vines": true,
		"projectile_type": Enums.Projectile.BULLETS,
		"attack_domains": [Enums.MovementTypes.LAND, Enums.MovementTypes.AIR],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.5,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.25,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.5,
			Enums.DamageTypes.MELEE: 0.5,
			Enums.DamageTypes.PLASMA: 0.25,
			Enums.DamageTypes.PRISM: 0.25,
			Enums.DamageTypes.RIFLE: 0.5,
			Enums.DamageTypes.ROCKET: 0.25,
			Enums.DamageTypes.TESLA: 0.25,
		},
		"costs": {"credits": 1200},
		"build_time": 30.0,
	},
}

const NAVY = {}

const CREEP_SPREAD_INTERVAL_TICKS: int = 10
const CREEP_SPREAD_TILES_PER_INTERVAL: int = 1
## Maximum vitality health a creep cell can hold.
## A cell's health is reset to this value by its owning source each spread tick.
const CREEP_CELL_MAX_HEALTH: int = 20
## How many game ticks between each global decay pass.
const CREEP_DECAY_INTERVAL_TICKS: int = 10
## Health lost per cell per decay pass when not vitalized by any source.
## A dead source's cells will disappear after MAX_HEALTH/DECAY_AMOUNT decay passes.
const CREEP_DECAY_AMOUNT: int = 1
const CREEP_REGEN_INTERVAL_TICKS: int = 10
const CREEP_REGEN_HP_PER_INTERVAL: int = 1
## How many ticks between off-creep damage checks for Radix structures.
const CREEP_OFF_CREEP_DAMAGE_INTERVAL_TICKS: int = 10
## Fraction of hp_max lost per interval when a structure is not on creep.
const CREEP_OFF_CREEP_DAMAGE_PERCENT: float = 0.005

## Ticks the Seedling spends playing the `build` animation before consuming
## itself into a structure or before transitioning to the `grow` phase.
const SEEDLING_BUILD_ANIM_TICKS: int = 10
## Ticks the Seedling spends playing the `grow` animation before transforming
## into a Sapling (only used by the spread ability).
const SEEDLING_GROW_ANIM_TICKS: int = 15
