class_name LegionConstants

const STRUCTURES = {
	Enums.SceneId.LEGION_COMMAND_CENTER:
	{
		"scene": "res://source/factions/the_legion/structures/CommandCenter.tscn",
		"unit_name": "Command Center",
		"description": "Central command hub. Builds structures and defences",
		"faction": Enums.Faction.LEGION,
		"production_tab_type": Enums.ProductionTabType.STRUCTURE,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F3,
		"produces": [Enums.ProductionTabType.STRUCTURE, Enums.ProductionTabType.DEFENCES],
		"structure_production_type": Enums.StructureProductionType.CONSTRUCT_OFF_FIELD_AND_TRICKLE,
		"max_concurrent_structures": 1,
		"sight_range": 10.0,
		"hp": 20,
		"hp_max": 20,
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.5,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.75,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.5,
			Enums.DamageTypes.MELEE: 0.75,
			Enums.DamageTypes.PLASMA: 0.25,
			Enums.DamageTypes.PRISM: 0.5,
			Enums.DamageTypes.RIFLE: 0.75,
			Enums.DamageTypes.ROCKET: 0.25,
			Enums.DamageTypes.TESLA: 0.25,
		},
		"costs": {"credits": 8},
		"energy_required": 0,
		"build_time": 10.0,
	},
	Enums.SceneId.LEGION_POWER_PLANT:
	{
		"scene": "res://source/factions/the_legion/structures/PowerPlant.tscn",
		"unit_name": "Power Plant",
		"description": "Generates energy to power other structures",
		"faction": Enums.Faction.LEGION,
		"production_tab_type": Enums.ProductionTabType.STRUCTURE,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F1,
		"sight_range": 6.0,
		"hp": 8,
		"hp_max": 8,
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.5,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.75,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.5,
			Enums.DamageTypes.MELEE: 0.75,
			Enums.DamageTypes.PLASMA: 0.25,
			Enums.DamageTypes.PRISM: 0.5,
			Enums.DamageTypes.RIFLE: 0.75,
			Enums.DamageTypes.ROCKET: 0.25,
			Enums.DamageTypes.TESLA: 0.25,
		},
		"costs": {"credits": 4},
		"energy_provided": 5,
		"build_time": 5.0,
	},
	Enums.SceneId.LEGION_BARRACKS:
	{
		"scene": "res://source/factions/the_legion/structures/Barracks.tscn",
		"unit_name": "legion_Barracks",
		"description": "Trains infantry units",
		"faction": Enums.Faction.LEGION,
		"production_tab_type": Enums.ProductionTabType.STRUCTURE,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F2,
		"sight_range": 8.0,
		"hp": 10,
		"hp_max": 10,
		"produces": [Enums.ProductionTabType.INFANTRY],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.5,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.75,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.5,
			Enums.DamageTypes.MELEE: 0.75,
			Enums.DamageTypes.PLASMA: 0.25,
			Enums.DamageTypes.PRISM: 0.5,
			Enums.DamageTypes.RIFLE: 0.75,
			Enums.DamageTypes.ROCKET: 0.25,
			Enums.DamageTypes.TESLA: 0.25,
		},
		"costs": {"credits": 4},
		"energy_required": 5,
		"structure_requirements":
		[
			Enums.SceneId.LEGION_COMMAND_CENTER,
			Enums.SceneId.LEGION_POWER_PLANT,
		],
		"build_time": 6.0,
	},
	Enums.SceneId.LEGION_REFINERY:
	{
		"scene": "res://source/factions/the_legion/structures/Refinery.tscn",
		"unit_name": "Refinery",
		"description": "Processes resources and deploys a Harvester.",
		"faction": Enums.Faction.LEGION,
		"production_tab_type": Enums.ProductionTabType.STRUCTURE,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F4,
		"sight_range": 8.0,
		"hp": 12,
		"hp_max": 12,
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.5,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.75,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.5,
			Enums.DamageTypes.MELEE: 0.75,
			Enums.DamageTypes.PLASMA: 0.25,
			Enums.DamageTypes.PRISM: 0.5,
			Enums.DamageTypes.RIFLE: 0.75,
			Enums.DamageTypes.ROCKET: 0.25,
			Enums.DamageTypes.TESLA: 0.25,
		},
		"costs": {"credits": 2000},
		"energy_required": 50,
		"structure_requirements":
		[
			Enums.SceneId.LEGION_COMMAND_CENTER,
			Enums.SceneId.LEGION_POWER_PLANT,
		],
		"build_time": 20.0,
	},
	Enums.SceneId.LEGION_FACTORY:
	{
		"scene": "res://source/factions/the_legion/structures/Factory.tscn",
		"unit_name": "Assembly",
		"description": "Produces Legion vehicles.",
		"faction": Enums.Faction.LEGION,
		"production_tab_type": Enums.ProductionTabType.STRUCTURE,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F5,
		"sight_range": 8.0,
		"hp": 12,
		"hp_max": 12,
		"produces": [Enums.ProductionTabType.VEHICLE],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.5,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.75,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.5,
			Enums.DamageTypes.MELEE: 0.75,
			Enums.DamageTypes.PLASMA: 0.25,
			Enums.DamageTypes.PRISM: 0.5,
			Enums.DamageTypes.RIFLE: 0.75,
			Enums.DamageTypes.ROCKET: 0.25,
			Enums.DamageTypes.TESLA: 0.25,
		},
		"costs": {"credits": 2000},
		"energy_required": 50,
		"structure_requirements":
		[
			Enums.SceneId.LEGION_COMMAND_CENTER,
			Enums.SceneId.LEGION_POWER_PLANT,
		],
		"build_time": 20.0,
	},
	Enums.SceneId.LEGION_AIRFIELD:
	{
		"scene": "res://source/factions/the_legion/structures/Airfield.tscn",
		"unit_name": "Airfield",
		"description": "Produces Legion aircraft.",
		"faction": Enums.Faction.LEGION,
		"production_tab_type": Enums.ProductionTabType.STRUCTURE,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F6,
		"sight_range": 8.0,
		"hp": 12,
		"hp_max": 12,
		"produces": [Enums.ProductionTabType.AIR],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.5,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.75,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.5,
			Enums.DamageTypes.MELEE: 0.75,
			Enums.DamageTypes.PLASMA: 0.25,
			Enums.DamageTypes.PRISM: 0.5,
			Enums.DamageTypes.RIFLE: 0.75,
			Enums.DamageTypes.ROCKET: 0.25,
			Enums.DamageTypes.TESLA: 0.25,
		},
		"costs": {"credits": 2000},
		"energy_required": 50,
		"structure_requirements":
		[
			Enums.SceneId.LEGION_COMMAND_CENTER,
			Enums.SceneId.LEGION_POWER_PLANT,
		],
		"build_time": 20.0,
	},
	Enums.SceneId.LEGION_DOCTRINE_SHRINE:
	{
		"scene": "res://source/factions/the_legion/structures/DoctrineShrine.tscn",
		"unit_name": "Doctrine Shrine",
		"description": "Tier 2 tech shrine. Unlocks doctrine upgrades and command auras.",
		"faction": Enums.Faction.LEGION,
		"production_tab_type": Enums.ProductionTabType.STRUCTURE,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F7,
		"sight_range": 9.0,
		"hp": 14,
		"hp_max": 14,
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.5,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.75,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.5,
			Enums.DamageTypes.MELEE: 0.75,
			Enums.DamageTypes.PLASMA: 0.25,
			Enums.DamageTypes.PRISM: 0.5,
			Enums.DamageTypes.RIFLE: 0.75,
			Enums.DamageTypes.ROCKET: 0.25,
			Enums.DamageTypes.TESLA: 0.25,
		},
		"costs": {"credits": 1500},
		"energy_required": 50,
		"structure_requirements":
		[
			Enums.SceneId.LEGION_COMMAND_CENTER,
			Enums.SceneId.LEGION_POWER_PLANT,
		],
		"build_time": 18.0,
	},
	Enums.SceneId.LEGION_GRAFTING_VAT:
	{
		"scene": "res://source/factions/the_legion/structures/GraftingVat.tscn",
		"unit_name": "Grafting Vat",
		"description": "Hybrid mutation lab. Unlocks Ascendant and elite hybrid tech.",
		"faction": Enums.Faction.LEGION,
		"production_tab_type": Enums.ProductionTabType.STRUCTURE,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F8,
		"sight_range": 8.0,
		"hp": 14,
		"hp_max": 14,
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.5,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.75,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.5,
			Enums.DamageTypes.MELEE: 0.75,
			Enums.DamageTypes.PLASMA: 0.25,
			Enums.DamageTypes.PRISM: 0.5,
			Enums.DamageTypes.RIFLE: 0.75,
			Enums.DamageTypes.ROCKET: 0.25,
			Enums.DamageTypes.TESLA: 0.25,
		},
		"costs": {"credits": 1800},
		"energy_required": 75,
		"structure_requirements":
		[
			Enums.SceneId.LEGION_COMMAND_CENTER,
			Enums.SceneId.LEGION_POWER_PLANT,
		],
		"build_time": 22.0,
	},
	Enums.SceneId.LEGION_SIGNAL_CHAPEL:
	{
		"scene": "res://source/factions/the_legion/structures/SignalChapel.tscn",
		"unit_name": "Signal Chapel",
		"description": "Detection and reveal support structure.",
		"faction": Enums.Faction.LEGION,
		"production_tab_type": Enums.ProductionTabType.STRUCTURE,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F9,
		"sight_range": 14.0,
		"hp": 12,
		"hp_max": 12,
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.25,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.5,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.25,
			Enums.DamageTypes.MELEE: 0.5,
			Enums.DamageTypes.PLASMA: 0.1,
			Enums.DamageTypes.PRISM: 0.25,
			Enums.DamageTypes.RIFLE: 0.5,
			Enums.DamageTypes.ROCKET: 0.1,
			Enums.DamageTypes.TESLA: 0.1,
		},
		"costs": {"credits": 1200},
		"energy_required": 50,
		"structure_requirements":
		[
			Enums.SceneId.LEGION_COMMAND_CENTER,
			Enums.SceneId.LEGION_POWER_PLANT,
		],
		"build_time": 16.0,
	},
}

const DEFENCES = {
	Enums.SceneId.LEGION_BASTION_WALL:
	{
		"scene": "res://source/factions/the_legion/structures/BastionWall.tscn",
		"unit_name": "Bastion Wall",
		"description": "Durable Legion wall segment. Shapes chokes and protects shrines.",
		"faction": Enums.Faction.LEGION,
		"production_tab_type": Enums.ProductionTabType.DEFENCES,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F1,
		"sight_range": 4.0,
		"hp": 14,
		"hp_max": 14,
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.5,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.5,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.5,
			Enums.DamageTypes.MELEE: 0.75,
			Enums.DamageTypes.PLASMA: 0.25,
			Enums.DamageTypes.PRISM: 0.25,
			Enums.DamageTypes.RIFLE: 0.75,
			Enums.DamageTypes.ROCKET: 0.25,
			Enums.DamageTypes.TESLA: 0.25,
		},
		"costs": {"credits": 100},
		"energy_required": 0,
		"structure_requirements":
		[
			Enums.SceneId.LEGION_COMMAND_CENTER,
		],
		"build_time": 6.0,
	},
	Enums.SceneId.LEGION_SANCTIFIED_GUN:
	{
		"scene": "res://source/factions/the_legion/structures/SanctifiedGun.tscn",
		"unit_name": "Sanctified Gun",
		"description": "Anti-infantry turret. Suppresses light ground at short range.",
		"faction": Enums.Faction.LEGION,
		"production_tab_type": Enums.ProductionTabType.DEFENCES,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F2,
		"sight_range": 9.0,
		"hp": 12,
		"hp_max": 12,
		"attack_damage": 8,
		"attack_type": "rifle",
		"attack_interval": 0.5,
		"attack_range": 6.0,
		"can_attack_vines": true,
		"projectile_type": Enums.Projectile.BULLETS,
		"attack_domains": [Enums.MovementTypes.LAND],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.25,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.5,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.25,
			Enums.DamageTypes.MELEE: 0.5,
			Enums.DamageTypes.PLASMA: 0.1,
			Enums.DamageTypes.PRISM: 0.25,
			Enums.DamageTypes.RIFLE: 0.5,
			Enums.DamageTypes.ROCKET: 0.1,
			Enums.DamageTypes.TESLA: 0.1,
		},
		"costs": {"credits": 400},
		"energy_required": 25,
		"structure_requirements":
		[
			Enums.SceneId.LEGION_COMMAND_CENTER,
			Enums.SceneId.LEGION_POWER_PLANT,
		],
		"build_time": 10.0,
	},
	Enums.SceneId.LEGION_PENITENT_CANNON:
	{
		"scene": "res://source/factions/the_legion/structures/PenitentCannon.tscn",
		"unit_name": "Penitent Cannon",
		"description": "Anti-vehicle defence. High-impact slow-firing cannon.",
		"faction": Enums.Faction.LEGION,
		"production_tab_type": Enums.ProductionTabType.DEFENCES,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F3,
		"sight_range": 10.0,
		"hp": 16,
		"hp_max": 16,
		"attack_damage": 45,
		"attack_type": "cannon",
		"attack_interval": 1.8,
		"attack_range": 8.0,
		"can_attack_vines": true,
		"projectile_type": Enums.Projectile.CANNON,
		"attack_domains": [Enums.MovementTypes.LAND],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.5,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.5,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.5,
			Enums.DamageTypes.MELEE: 0.75,
			Enums.DamageTypes.PLASMA: 0.25,
			Enums.DamageTypes.PRISM: 0.25,
			Enums.DamageTypes.RIFLE: 0.75,
			Enums.DamageTypes.ROCKET: 0.25,
			Enums.DamageTypes.TESLA: 0.25,
		},
		"costs": {"credits": 600},
		"energy_required": 35,
		"structure_requirements":
		[
			Enums.SceneId.LEGION_COMMAND_CENTER,
			Enums.SceneId.LEGION_POWER_PLANT,
		],
		"build_time": 12.0,
	},
	Enums.SceneId.LEGION_SKY_LANCE:
	{
		"scene": "res://source/factions/the_legion/structures/SkyLance.tscn",
		"unit_name": "Sky Lance",
		"description": "Anti-air missile battery. Protects reactors and bases from aircraft.",
		"faction": Enums.Faction.LEGION,
		"production_tab_type": Enums.ProductionTabType.DEFENCES,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F4,
		"sight_range": 11.0,
		"hp": 12,
		"hp_max": 12,
		"attack_damage": 22,
		"attack_type": "rocket",
		"attack_interval": 0.9,
		"attack_range": 9.0,
		"can_attack_vines": false,
		"projectile_type": Enums.Projectile.ROCKET,
		"attack_domains": [Enums.MovementTypes.AIR],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.25,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.5,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.25,
			Enums.DamageTypes.MELEE: 0.5,
			Enums.DamageTypes.PLASMA: 0.1,
			Enums.DamageTypes.PRISM: 0.25,
			Enums.DamageTypes.RIFLE: 0.5,
			Enums.DamageTypes.ROCKET: 0.1,
			Enums.DamageTypes.TESLA: 0.1,
		},
		"costs": {"credits": 500},
		"energy_required": 30,
		"structure_requirements":
		[
			Enums.SceneId.LEGION_COMMAND_CENTER,
			Enums.SceneId.LEGION_POWER_PLANT,
		],
		"build_time": 11.0,
	},
	Enums.SceneId.LEGION_DOCTRINE_BEACON:
	{
		"scene": "res://source/factions/the_legion/structures/DoctrineBeacon.tscn",
		"unit_name": "Doctrine Beacon",
		"description": "Aura support structure. Buffs nearby Legion units and construction.",
		"faction": Enums.Faction.LEGION,
		"production_tab_type": Enums.ProductionTabType.DEFENCES,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F5,
		"sight_range": 7.0,
		"hp": 10,
		"hp_max": 10,
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.25,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.5,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.25,
			Enums.DamageTypes.MELEE: 0.5,
			Enums.DamageTypes.PLASMA: 0.1,
			Enums.DamageTypes.PRISM: 0.25,
			Enums.DamageTypes.RIFLE: 0.5,
			Enums.DamageTypes.ROCKET: 0.1,
			Enums.DamageTypes.TESLA: 0.1,
		},
		"costs": {"credits": 450},
		"energy_required": 25,
		"structure_requirements":
		[
			Enums.SceneId.LEGION_COMMAND_CENTER,
			Enums.SceneId.LEGION_POWER_PLANT,
		],
		"build_time": 10.0,
	},
	Enums.SceneId.LEGION_VIGIL_CHAPEL:
	{
		"scene": "res://source/factions/the_legion/structures/VigilChapel.tscn",
		"unit_name": "Vigil Chapel",
		"description": "Static detection defence. Reveals stealth, mines, and burrowed threats.",
		"faction": Enums.Faction.LEGION,
		"production_tab_type": Enums.ProductionTabType.DEFENCES,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F6,
		"sight_range": 13.0,
		"hp": 12,
		"hp_max": 12,
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.25,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.5,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.25,
			Enums.DamageTypes.MELEE: 0.5,
			Enums.DamageTypes.PLASMA: 0.1,
			Enums.DamageTypes.PRISM: 0.25,
			Enums.DamageTypes.RIFLE: 0.5,
			Enums.DamageTypes.ROCKET: 0.1,
			Enums.DamageTypes.TESLA: 0.1,
		},
		"costs": {"credits": 450},
		"energy_required": 25,
		"structure_requirements":
		[
			Enums.SceneId.LEGION_COMMAND_CENTER,
			Enums.SceneId.LEGION_POWER_PLANT,
		],
		"build_time": 10.0,
	},
}

const INFANTRY = {
	Enums.SceneId.LEGION_SOLDIER:
	{
		"scene": "res://source/factions/the_legion/units/Soldier.tscn",
		"unit_name": "legion_Soldier",
		"description": "Light infantry armed with a laser rifle",
		"faction": Enums.Faction.LEGION,
		"production_tab_type": Enums.ProductionTabType.INFANTRY,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F1,
		"sight_range": 8.0,
		"hp": 5,
		"hp_max": 5,
		"can_move_through_vines": true,
		"attack_damage": 1,
		"attack_type": "laser",
		"attack_interval": 0.55,
		"attack_range": 4.0,
		"can_attack_vines": true,
		"projectile_type": Enums.Projectile.LASER,
		"projectile_origin": Vector3(-0.22, 0.3, -0.1),
		"projectile_config":
		{
			"color": Color("1034a6ff"),
			"laser_count": 2,
			"laser_width": 0.03,
			"laser_duration": 0.25,
			"sound_start": preload("res://assets/sound_effects/laser-shot.mp3"),
		},
		"rotation_speed": 1,
		"attack_domains":
		[
			Enums.MovementTypes.LAND,
		],
		"armor":
		{
			Enums.DamageTypes.LASER: 0.5,
		},
		"costs": {"credits": 2},
		"build_time": 3.0,
	},
	Enums.SceneId.LEGION_FIELD_ENGINEER:
	{
		"scene": "res://source/factions/the_legion/units/FieldEngineer.tscn",
		"unit_name": "Field Engineer",
		"description": "Captures neutral or enemy structures and assists forward construction.",
		"faction": Enums.Faction.LEGION,
		"production_tab_type": Enums.ProductionTabType.INFANTRY,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F2,
		"sight_range": 7.0,
		"hp": 100,
		"hp_max": 100,
		"can_move_through_vines": true,
		"movement_domains": [Enums.MovementTypes.LAND],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.0,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.0,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.0,
			Enums.DamageTypes.MELEE: 0.0,
			Enums.DamageTypes.PLASMA: 0.0,
			Enums.DamageTypes.PRISM: 0.0,
			Enums.DamageTypes.RIFLE: 0.0,
			Enums.DamageTypes.ROCKET: 0.0,
			Enums.DamageTypes.TESLA: 0.0,
		},
		"costs": {"credits": 130},
		"build_time": 11.0,
	},
	Enums.SceneId.LEGION_ACOLYTE_GUARD:
	{
		"scene": "res://source/factions/the_legion/units/AcolyteGuard.tscn",
		"unit_name": "Acolyte Guard",
		"description": "Disciplined melee frontline. Holds shrines and choke points.",
		"faction": Enums.Faction.LEGION,
		"production_tab_type": Enums.ProductionTabType.INFANTRY,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F3,
		"sight_range": 6.0,
		"hp": 200,
		"hp_max": 200,
		"can_move_through_vines": true,
		"attack_damage": 16,
		"attack_type": "melee",
		"attack_interval": 1.0,
		"attack_range": 1.4,
		"attack_domains": [Enums.MovementTypes.LAND],
		"movement_domains": [Enums.MovementTypes.LAND],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.25,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.25,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.25,
			Enums.DamageTypes.MELEE: 0.5,
			Enums.DamageTypes.PLASMA: 0.1,
			Enums.DamageTypes.PRISM: 0.1,
			Enums.DamageTypes.RIFLE: 0.5,
			Enums.DamageTypes.ROCKET: 0.1,
			Enums.DamageTypes.TESLA: 0.1,
		},
		"costs": {"credits": 160},
		"build_time": 12.0,
	},
	Enums.SceneId.LEGION_CONFESSOR_ROCKET_TEAM:
	{
		"scene": "res://source/factions/the_legion/units/ConfessorRocketTeam.tscn",
		"unit_name": "Confessor Rocket Team",
		"description": "Anti-armor and anti-air rocket squad.",
		"faction": Enums.Faction.LEGION,
		"production_tab_type": Enums.ProductionTabType.INFANTRY,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F4,
		"sight_range": 8.0,
		"hp": 110,
		"hp_max": 110,
		"can_move_through_vines": true,
		"attack_damage": 30,
		"attack_type": "rocket",
		"attack_interval": 1.8,
		"attack_range": 6.0,
		"projectile_type": Enums.Projectile.ROCKET,
		"attack_domains": [Enums.MovementTypes.LAND, Enums.MovementTypes.AIR],
		"movement_domains": [Enums.MovementTypes.LAND],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.0,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.0,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.0,
			Enums.DamageTypes.MELEE: 0.0,
			Enums.DamageTypes.PLASMA: 0.0,
			Enums.DamageTypes.PRISM: 0.0,
			Enums.DamageTypes.RIFLE: 0.0,
			Enums.DamageTypes.ROCKET: 0.0,
			Enums.DamageTypes.TESLA: 0.0,
		},
		"costs": {"credits": 200},
		"build_time": 14.0,
	},
	Enums.SceneId.LEGION_PURIFIER_SQUAD:
	{
		"scene": "res://source/factions/the_legion/units/PurifierSquad.tscn",
		"unit_name": "Purifier Squad",
		"description": "AoE corrosive anti-swarm and feral-growth cleanser.",
		"faction": Enums.Faction.LEGION,
		"production_tab_type": Enums.ProductionTabType.INFANTRY,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F5,
		"sight_range": 7.0,
		"hp": 110,
		"hp_max": 110,
		"can_move_through_vines": true,
		"attack_damage": 18,
		"attack_type": "corrosive",
		"attack_interval": 1.4,
		"attack_range": 5.0,
		"can_attack_vines": true,
		"projectile_type": Enums.Projectile.BULLETS,
		"attack_domains": [Enums.MovementTypes.LAND],
		"movement_domains": [Enums.MovementTypes.LAND],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.0,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.0,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.0,
			Enums.DamageTypes.MELEE: 0.0,
			Enums.DamageTypes.PLASMA: 0.0,
			Enums.DamageTypes.PRISM: 0.0,
			Enums.DamageTypes.RIFLE: 0.0,
			Enums.DamageTypes.ROCKET: 0.0,
			Enums.DamageTypes.TESLA: 0.0,
		},
		"costs": {"credits": 200},
		"build_time": 14.0,
	},
	Enums.SceneId.LEGION_CHAPLAIN_MEDIC:
	{
		"scene": "res://source/factions/the_legion/units/ChaplainMedic.tscn",
		"unit_name": "Chaplain Medic",
		"description": "Sustain and morale aura support; heals nearby Legion infantry.",
		"faction": Enums.Faction.LEGION,
		"production_tab_type": Enums.ProductionTabType.INFANTRY,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F6,
		"sight_range": 8.0,
		"hp": 100,
		"hp_max": 100,
		"can_move_through_vines": true,
		"movement_domains": [Enums.MovementTypes.LAND],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.0,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.0,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.0,
			Enums.DamageTypes.MELEE: 0.0,
			Enums.DamageTypes.PLASMA: 0.0,
			Enums.DamageTypes.PRISM: 0.0,
			Enums.DamageTypes.RIFLE: 0.0,
			Enums.DamageTypes.ROCKET: 0.0,
			Enums.DamageTypes.TESLA: 0.0,
		},
		"costs": {"credits": 220},
		"build_time": 14.0,
	},
	Enums.SceneId.LEGION_ASCENDANT:
	{
		"scene": "res://source/factions/the_legion/units/Ascendant.tscn",
		"unit_name": "Ascendant",
		"description": "Elite hybrid shock unit. Limited count, dramatic spearhead.",
		"faction": Enums.Faction.LEGION,
		"production_tab_type": Enums.ProductionTabType.INFANTRY,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F7,
		"sight_range": 9.0,
		"hp": 320,
		"hp_max": 320,
		"can_move_through_vines": true,
		"attack_damage": 35,
		"attack_type": "plasma",
		"attack_interval": 1.0,
		"attack_range": 5.0,
		"can_attack_vines": true,
		"projectile_type": Enums.Projectile.BULLETS,
		"attack_domains": [Enums.MovementTypes.LAND, Enums.MovementTypes.AIR],
		"movement_domains": [Enums.MovementTypes.LAND],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.25,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.25,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.25,
			Enums.DamageTypes.MELEE: 0.5,
			Enums.DamageTypes.PLASMA: 0.25,
			Enums.DamageTypes.PRISM: 0.25,
			Enums.DamageTypes.RIFLE: 0.5,
			Enums.DamageTypes.ROCKET: 0.1,
			Enums.DamageTypes.TESLA: 0.1,
		},
		"costs": {"credits": 350},
		"build_time": 20.0,
	},
}

const VEHICLES = {
	Enums.SceneId.LEGION_HARVESTER:
	{
		"scene": "res://source/factions/the_legion/units/Harvester.tscn",
		"unit_name": "Harvester",
		"description": "Unarmed resource gathering vehicle.",
		"faction": Enums.Faction.LEGION,
		"production_tab_type": Enums.ProductionTabType.VEHICLE,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F1,
		"sight_range": 5.0,
		"hp": 600,
		"hp_max": 600,
		"resources_max": 500,
		"resources_gather_rate": 250,
		"can_move_through_vines": true,
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.0,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.0,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.0,
			Enums.DamageTypes.MELEE: 0.0,
			Enums.DamageTypes.PLASMA: 0.0,
			Enums.DamageTypes.PRISM: 0.0,
			Enums.DamageTypes.RIFLE: 0.0,
			Enums.DamageTypes.ROCKET: 0.0,
			Enums.DamageTypes.TESLA: 0.0,
		},
		"costs": {"credits": 2},
		"build_time": 3.0,
	},
	Enums.SceneId.LEGION_FORWARD_COMMAND_VEHICLE:
	{
		"scene": "res://source/factions/the_legion/units/ForwardCommandVehicle.tscn",
		"unit_name": "Forward Command Vehicle",
		"description": "Deploys to create a forward Legion build radius.",
		"faction": Enums.Faction.LEGION,
		"production_tab_type": Enums.ProductionTabType.VEHICLE,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F2,
		"sight_range": 8.0,
		"hp": 500,
		"hp_max": 500,
		"movement_domains": [Enums.MovementTypes.LAND],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.25,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.5,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.25,
			Enums.DamageTypes.MELEE: 0.5,
			Enums.DamageTypes.PLASMA: 0.1,
			Enums.DamageTypes.PRISM: 0.25,
			Enums.DamageTypes.RIFLE: 0.5,
			Enums.DamageTypes.ROCKET: 0.1,
			Enums.DamageTypes.TESLA: 0.1,
		},
		"costs": {"credits": 600},
		"build_time": 18.0,
	},
	Enums.SceneId.LEGION_PURSUIT_BUGGY:
	{
		"scene": "res://source/factions/the_legion/units/PursuitBuggy.tscn",
		"unit_name": "Pursuit Buggy",
		"description": "Fast scout and harasser. Hunts stragglers and patrols.",
		"faction": Enums.Faction.LEGION,
		"production_tab_type": Enums.ProductionTabType.VEHICLE,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F3,
		"sight_range": 9.0,
		"hp": 220,
		"hp_max": 220,
		"attack_damage": 8,
		"attack_type": "rifle",
		"attack_interval": 0.4,
		"attack_range": 5.0,
		"can_attack_vines": true,
		"projectile_type": Enums.Projectile.BULLETS,
		"attack_domains": [Enums.MovementTypes.LAND],
		"movement_domains": [Enums.MovementTypes.LAND],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.0,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.0,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.0,
			Enums.DamageTypes.MELEE: 0.0,
			Enums.DamageTypes.PLASMA: 0.0,
			Enums.DamageTypes.PRISM: 0.0,
			Enums.DamageTypes.RIFLE: 0.0,
			Enums.DamageTypes.ROCKET: 0.0,
			Enums.DamageTypes.TESLA: 0.0,
		},
		"costs": {"credits": 250},
		"build_time": 12.0,
	},
	Enums.SceneId.LEGION_CRUCIBLE_APC:
	{
		"scene": "res://source/factions/the_legion/units/CrucibleAPC.tscn",
		"unit_name": "Crucible APC",
		"description": "Infantry transport with firing-port option for urban breaches.",
		"faction": Enums.Faction.LEGION,
		"production_tab_type": Enums.ProductionTabType.VEHICLE,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F4,
		"sight_range": 7.0,
		"hp": 380,
		"hp_max": 380,
		"movement_domains": [Enums.MovementTypes.LAND],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.25,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.25,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.25,
			Enums.DamageTypes.MELEE: 0.5,
			Enums.DamageTypes.PLASMA: 0.1,
			Enums.DamageTypes.PRISM: 0.1,
			Enums.DamageTypes.RIFLE: 0.5,
			Enums.DamageTypes.ROCKET: 0.1,
			Enums.DamageTypes.TESLA: 0.1,
		},
		"costs": {"credits": 350},
		"build_time": 16.0,
	},
	Enums.SceneId.LEGION_SANCTIFIER_TANK:
	{
		"scene": "res://source/factions/the_legion/units/SanctifierTank.tscn",
		"unit_name": "Sanctifier Tank",
		"description": "Durable midgame backbone armor. Doctrine-upgradable cannon.",
		"faction": Enums.Faction.LEGION,
		"production_tab_type": Enums.ProductionTabType.VEHICLE,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F5,
		"sight_range": 8.0,
		"hp": 480,
		"hp_max": 480,
		"attack_damage": 35,
		"attack_type": "cannon",
		"attack_interval": 1.4,
		"attack_range": 6.0,
		"can_attack_vines": true,
		"projectile_type": Enums.Projectile.CANNON,
		"attack_domains": [Enums.MovementTypes.LAND],
		"movement_domains": [Enums.MovementTypes.LAND],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.5,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.5,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.5,
			Enums.DamageTypes.MELEE: 0.5,
			Enums.DamageTypes.PLASMA: 0.25,
			Enums.DamageTypes.PRISM: 0.25,
			Enums.DamageTypes.RIFLE: 0.5,
			Enums.DamageTypes.ROCKET: 0.25,
			Enums.DamageTypes.TESLA: 0.25,
		},
		"costs": {"credits": 400},
		"build_time": 18.0,
	},
	Enums.SceneId.LEGION_BASILISK_ARTILLERY:
	{
		"scene": "res://source/factions/the_legion/units/BasiliskArtillery.tscn",
		"unit_name": "Basilisk Artillery",
		"description": "Long-range siege vehicle vs nests, bunkers, and turrets.",
		"faction": Enums.Faction.LEGION,
		"production_tab_type": Enums.ProductionTabType.VEHICLE,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F6,
		"sight_range": 9.0,
		"hp": 320,
		"hp_max": 320,
		"attack_damage": 60,
		"attack_type": "explosive",
		"attack_interval": 2.5,
		"attack_range": 10.0,
		"can_attack_vines": true,
		"projectile_type": Enums.Projectile.ROCKET,
		"attack_domains": [Enums.MovementTypes.LAND],
		"movement_domains": [Enums.MovementTypes.LAND],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.25,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.25,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.25,
			Enums.DamageTypes.MELEE: 0.25,
			Enums.DamageTypes.PLASMA: 0.1,
			Enums.DamageTypes.PRISM: 0.1,
			Enums.DamageTypes.RIFLE: 0.25,
			Enums.DamageTypes.ROCKET: 0.1,
			Enums.DamageTypes.TESLA: 0.1,
		},
		"costs": {"credits": 600},
		"build_time": 22.0,
	},
	Enums.SceneId.LEGION_RELIQUARY_WALKER:
	{
		"scene": "res://source/factions/the_legion/units/ReliquaryWalker.tscn",
		"unit_name": "Reliquary Walker",
		"description": "Slow heavy walker; mobile shrine with army-buffing aura.",
		"faction": Enums.Faction.LEGION,
		"production_tab_type": Enums.ProductionTabType.VEHICLE,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F7,
		"sight_range": 10.0,
		"hp": 1100,
		"hp_max": 1100,
		"attack_damage": 50,
		"attack_type": "plasma",
		"attack_interval": 1.6,
		"attack_range": 7.0,
		"can_attack_vines": true,
		"projectile_type": Enums.Projectile.BULLETS,
		"attack_domains": [Enums.MovementTypes.LAND, Enums.MovementTypes.AIR],
		"movement_domains": [Enums.MovementTypes.LAND],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.5,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.5,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.5,
			Enums.DamageTypes.MELEE: 0.75,
			Enums.DamageTypes.PLASMA: 0.25,
			Enums.DamageTypes.PRISM: 0.25,
			Enums.DamageTypes.RIFLE: 0.75,
			Enums.DamageTypes.ROCKET: 0.25,
			Enums.DamageTypes.TESLA: 0.25,
		},
		"costs": {"credits": 1100},
		"build_time": 30.0,
	},
}

const AIR = {
	Enums.SceneId.LEGION_SERAPH:
	{
		"scene": "res://source/factions/the_legion/units/Seraph.tscn",
		"unit_name": "Seraph",
		"description": "Air harasser. Strong vs ground infantry and air.",
		"faction": Enums.Faction.LEGION,
		"production_tab_type": Enums.ProductionTabType.AIR,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F1,
		"sight_range": 9.0,
		"hp": 320,
		"hp_max": 320,
		"movement_domains": [Enums.MovementTypes.AIR],
		"attack_damage": 18,
		"attack_type": "laser",
		"attack_interval": 0.5,
		"attack_range": 6.0,
		"projectile_type": Enums.Projectile.LASER,
		"attack_domains": [Enums.MovementTypes.LAND, Enums.MovementTypes.AIR],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.0,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.0,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.0,
			Enums.DamageTypes.MELEE: 0.0,
			Enums.DamageTypes.PLASMA: 0.0,
			Enums.DamageTypes.PRISM: 0.0,
			Enums.DamageTypes.RIFLE: 0.0,
			Enums.DamageTypes.ROCKET: 0.0,
			Enums.DamageTypes.TESLA: 0.0,
		},
		"costs": {"credits": 350},
		"build_time": 16.0,
	},
	Enums.SceneId.LEGION_BOMBER:
	{
		"scene": "res://source/factions/the_legion/units/Bomber.tscn",
		"unit_name": "Bomber",
		"description": "Heavy bomber vs structures and clusters. Cannot attack air.",
		"faction": Enums.Faction.LEGION,
		"production_tab_type": Enums.ProductionTabType.AIR,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F2,
		"sight_range": 10.0,
		"hp": 420,
		"hp_max": 420,
		"movement_domains": [Enums.MovementTypes.AIR],
		"attack_damage": 70,
		"attack_type": "explosive",
		"attack_interval": 2.5,
		"attack_range": 4.0,
		"can_attack_vines": true,
		"projectile_type": Enums.Projectile.ROCKET,
		"attack_domains": [Enums.MovementTypes.LAND],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.25,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.25,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.25,
			Enums.DamageTypes.MELEE: 0.25,
			Enums.DamageTypes.PLASMA: 0.1,
			Enums.DamageTypes.PRISM: 0.1,
			Enums.DamageTypes.RIFLE: 0.25,
			Enums.DamageTypes.ROCKET: 0.1,
			Enums.DamageTypes.TESLA: 0.1,
		},
		"costs": {"credits": 500},
		"build_time": 20.0,
	},
	Enums.SceneId.LEGION_TRANSPORTER:
	{
		"scene": "res://source/factions/the_legion/units/Transporter.tscn",
		"unit_name": "Transporter",
		"description": "Air transport for vehicles and infantry. Cannot attack.",
		"faction": Enums.Faction.LEGION,
		"production_tab_type": Enums.ProductionTabType.AIR,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F3,
		"sight_range": 8.0,
		"hp": 450,
		"hp_max": 450,
		"movement_domains": [Enums.MovementTypes.AIR],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.0,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.0,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.0,
			Enums.DamageTypes.MELEE: 0.0,
			Enums.DamageTypes.PLASMA: 0.0,
			Enums.DamageTypes.PRISM: 0.0,
			Enums.DamageTypes.RIFLE: 0.0,
			Enums.DamageTypes.ROCKET: 0.0,
			Enums.DamageTypes.TESLA: 0.0,
		},
		"costs": {"credits": 400},
		"build_time": 18.0,
	},
	Enums.SceneId.LEGION_ARCHANGEL_GUNSHIP:
	{
		"scene": "res://source/factions/the_legion/units/ArchangelGunship.tscn",
		"unit_name": "Archangel Gunship",
		"description": "T3 capital air finisher. Heavy multi-weapon platform.",
		"faction": Enums.Faction.LEGION,
		"production_tab_type": Enums.ProductionTabType.AIR,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F4,
		"sight_range": 12.0,
		"hp": 950,
		"hp_max": 950,
		"movement_domains": [Enums.MovementTypes.AIR],
		"attack_damage": 55,
		"attack_type": "plasma",
		"attack_interval": 1.0,
		"attack_range": 8.0,
		"can_attack_vines": true,
		"projectile_type": Enums.Projectile.BULLETS,
		"attack_domains": [Enums.MovementTypes.LAND, Enums.MovementTypes.AIR],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.5,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.25,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.5,
			Enums.DamageTypes.MELEE: 0.5,
			Enums.DamageTypes.PLASMA: 0.25,
			Enums.DamageTypes.PRISM: 0.25,
			Enums.DamageTypes.RIFLE: 0.5,
			Enums.DamageTypes.ROCKET: 0.25,
			Enums.DamageTypes.TESLA: 0.25,
		},
		"costs": {"credits": 1200},
		"build_time": 30.0,
	},
}

const NAVY = {}
