class_name RemnantConstants

const SOUND_ROCKET_START = preload("res://assets/sound_effects/rocket1_start.mp3")
const SOUND_ROCKET_END = preload("res://assets/sound_effects/rocket1_end.mp3")

const STRUCTURES = {
	Enums.SceneId.REMNANTS_COMMAND_CENTER:
	{
		"scene": "res://source/factions/the_remnants/structures/CommandCenter.tscn",
		"unit_name": "remnants_CommandCenter",
		"description": "Central command hub. Builds structures and defences",
		"faction": Enums.Faction.REMNANTS,
		"production_tab_type": Enums.ProductionTabType.STRUCTURE,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F1,
		"produces": [Enums.ProductionTabType.STRUCTURE, Enums.ProductionTabType.DEFENCES],
		"structure_production_type": Enums.StructureProductionType.CONSTRUCT_OFF_FIELD_AND_TRICKLE,
		"max_concurrent_structures": 1,
		"sight_range": 10.0,
		"hp": 20,
		"hp_max": 20,
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.5,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.75,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.5,
			Enums.DamageTypes.MELEE: 0.75,
			Enums.DamageTypes.PLASMA: 0.25,
			Enums.DamageTypes.PRISM: 0.5,
			Enums.DamageTypes.RIFLE: 0.75,
			Enums.DamageTypes.ROCKET: 0.25,
			Enums.DamageTypes.TESLA: 0.25,
		},
		"costs": {"credits": 8},
		"build_time": 10.0,
	},
	Enums.SceneId.REMNANTS_CASERN:
	{
		"scene": "res://source/factions/the_remnants/structures/Casern.tscn",
		"unit_name": "Casern",
		"description": "Trains Remnants infantry units",
		"faction": Enums.Faction.REMNANTS,
		"production_tab_type": Enums.ProductionTabType.STRUCTURE,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F2,
		"produces": [Enums.ProductionTabType.INFANTRY],
		"sight_range": 8.0,
		"hp": 10,
		"hp_max": 10,
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.5,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.75,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.5,
			Enums.DamageTypes.MELEE: 0.75,
			Enums.DamageTypes.PLASMA: 0.25,
			Enums.DamageTypes.PRISM: 0.5,
			Enums.DamageTypes.RIFLE: 0.75,
			Enums.DamageTypes.ROCKET: 0.25,
			Enums.DamageTypes.TESLA: 0.25,
		},
		"costs": {"credits": 600},
		"energy_required": 25,
		"structure_requirements":
		[
			Enums.SceneId.REMNANTS_COMMAND_CENTER,
		],
		"build_time": 6.0,
	},
	Enums.SceneId.REMNANTS_FACTORY:
	{
		"scene": "res://source/factions/the_remnants/structures/Factory.tscn",
		"unit_name": "Factory",
		"description": "Produces Remnants vehicles",
		"faction": Enums.Faction.REMNANTS,
		"production_tab_type": Enums.ProductionTabType.STRUCTURE,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F3,
		"produces": [Enums.ProductionTabType.VEHICLE],
		"sight_range": 8.0,
		"hp": 12,
		"hp_max": 12,
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.5,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.75,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.5,
			Enums.DamageTypes.MELEE: 0.75,
			Enums.DamageTypes.PLASMA: 0.25,
			Enums.DamageTypes.PRISM: 0.5,
			Enums.DamageTypes.RIFLE: 0.75,
			Enums.DamageTypes.ROCKET: 0.25,
			Enums.DamageTypes.TESLA: 0.25,
		},
		"costs": {"credits": 2000},
		"energy_required": 50,
		"structure_requirements":
		[
			Enums.SceneId.REMNANTS_COMMAND_CENTER,
		],
		"build_time": 20.0,
	},
	Enums.SceneId.REMNANTS_DRONE_TOWER:
	{
		"scene": "res://source/factions/the_remnants/structures/DroneTower.tscn",
		"unit_name": "Drone Tower",
		"description": "Produces Remnants air units",
		"faction": Enums.Faction.REMNANTS,
		"production_tab_type": Enums.ProductionTabType.STRUCTURE,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F4,
		"produces": [Enums.ProductionTabType.AIR],
		"sight_range": 8.0,
		"hp": 12,
		"hp_max": 12,
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.5,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.75,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.5,
			Enums.DamageTypes.MELEE: 0.75,
			Enums.DamageTypes.PLASMA: 0.25,
			Enums.DamageTypes.PRISM: 0.5,
			Enums.DamageTypes.RIFLE: 0.75,
			Enums.DamageTypes.ROCKET: 0.25,
			Enums.DamageTypes.TESLA: 0.25,
		},
		"costs": {"credits": 2000},
		"energy_required": 50,
		"structure_requirements":
		[
			Enums.SceneId.REMNANTS_COMMAND_CENTER,
		],
		"build_time": 20.0,
	},
	Enums.SceneId.REMNANTS_FIELD_GENERATOR:
	{
		"scene": "res://source/factions/the_remnants/structures/Reactor.tscn",
		"unit_name": "Reactor",
		"description": "Power supply for Remnants bases.",
		"faction": Enums.Faction.REMNANTS,
		"production_tab_type": Enums.ProductionTabType.STRUCTURE,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F5,
		"sight_range": 7.0,
		"hp": 12,
		"hp_max": 12,
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.25,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.5,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.25,
			Enums.DamageTypes.MELEE: 0.5,
			Enums.DamageTypes.PLASMA: 0.1,
			Enums.DamageTypes.PRISM: 0.25,
			Enums.DamageTypes.RIFLE: 0.5,
			Enums.DamageTypes.ROCKET: 0.1,
			Enums.DamageTypes.TESLA: 0.1,
		},
		"costs": {"credits": 500},
		"energy_required": 0,
		"structure_requirements":
		[
			Enums.SceneId.REMNANTS_COMMAND_CENTER,
		],
		"build_time": 10.0,
	},
	Enums.SceneId.REMNANTS_SALVAGE_YARD:
	{
		"scene": "res://source/factions/the_remnants/structures/SalvageYard.tscn",
		"unit_name": "Salvage Yard",
		"description": "Repair drones, dismantling, and scrap economy hub.",
		"faction": Enums.Faction.REMNANTS,
		"production_tab_type": Enums.ProductionTabType.STRUCTURE,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F6,
		"sight_range": 7.0,
		"hp": 14,
		"hp_max": 14,
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.5,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.75,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.5,
			Enums.DamageTypes.MELEE: 0.75,
			Enums.DamageTypes.PLASMA: 0.25,
			Enums.DamageTypes.PRISM: 0.5,
			Enums.DamageTypes.RIFLE: 0.75,
			Enums.DamageTypes.ROCKET: 0.25,
			Enums.DamageTypes.TESLA: 0.25,
		},
		"costs": {"credits": 800},
		"energy_required": 25,
		"structure_requirements":
		[
			Enums.SceneId.REMNANTS_COMMAND_CENTER,
		],
		"build_time": 14.0,
	},
	Enums.SceneId.REMNANTS_RADAR_MAST:
	{
		"scene": "res://source/factions/the_remnants/structures/RadarMast.tscn",
		"unit_name": "Radar Mast",
		"description": "Detector and map vision support.",
		"faction": Enums.Faction.REMNANTS,
		"production_tab_type": Enums.ProductionTabType.STRUCTURE,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F7,
		"sight_range": 16.0,
		"hp": 10,
		"hp_max": 10,
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.25,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.5,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.25,
			Enums.DamageTypes.MELEE: 0.5,
			Enums.DamageTypes.PLASMA: 0.1,
			Enums.DamageTypes.PRISM: 0.25,
			Enums.DamageTypes.RIFLE: 0.5,
			Enums.DamageTypes.ROCKET: 0.1,
			Enums.DamageTypes.TESLA: 0.1,
		},
		"costs": {"credits": 600},
		"energy_required": 25,
		"structure_requirements":
		[
			Enums.SceneId.REMNANTS_COMMAND_CENTER,
		],
		"build_time": 12.0,
	},
	Enums.SceneId.REMNANTS_COMMAND_POST:
	{
		"scene": "res://source/factions/the_remnants/structures/CommandPost.tscn",
		"unit_name": "Command Post",
		"description": "Forward base unlocking local complex construction.",
		"faction": Enums.Faction.REMNANTS,
		"production_tab_type": Enums.ProductionTabType.STRUCTURE,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F8,
		"sight_range": 9.0,
		"hp": 16,
		"hp_max": 16,
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.5,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.75,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.5,
			Enums.DamageTypes.MELEE: 0.75,
			Enums.DamageTypes.PLASMA: 0.25,
			Enums.DamageTypes.PRISM: 0.5,
			Enums.DamageTypes.RIFLE: 0.75,
			Enums.DamageTypes.ROCKET: 0.25,
			Enums.DamageTypes.TESLA: 0.25,
		},
		"costs": {"credits": 1200},
		"energy_required": 50,
		"structure_requirements":
		[
			Enums.SceneId.REMNANTS_COMMAND_CENTER,
		],
		"build_time": 18.0,
	},
}

const DEFENCES = {
	Enums.SceneId.REMNANTS_WALL_GATE:
	{
		"scene": "res://source/factions/the_remnants/structures/WallGate.tscn",
		"unit_name": "Wall / Gate",
		"description": "Blocker and access-control segment.",
		"faction": Enums.Faction.REMNANTS,
		"production_tab_type": Enums.ProductionTabType.DEFENCES,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F1,
		"sight_range": 4.0,
		"hp": 12,
		"hp_max": 12,
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.5,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.5,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.5,
			Enums.DamageTypes.MELEE: 0.75,
			Enums.DamageTypes.PLASMA: 0.25,
			Enums.DamageTypes.PRISM: 0.25,
			Enums.DamageTypes.RIFLE: 0.75,
			Enums.DamageTypes.ROCKET: 0.25,
			Enums.DamageTypes.TESLA: 0.25,
		},
		"costs": {"credits": 80},
		"energy_required": 0,
		"structure_requirements":
		[
			Enums.SceneId.REMNANTS_COMMAND_CENTER,
		],
		"build_time": 5.0,
	},
	Enums.SceneId.REMNANTS_BUNKER:
	{
		"scene": "res://source/factions/the_remnants/structures/Bunker.tscn",
		"unit_name": "Bunker",
		"description": "Garrison defence; infantry shelter and firing point.",
		"faction": Enums.Faction.REMNANTS,
		"production_tab_type": Enums.ProductionTabType.DEFENCES,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F2,
		"sight_range": 8.0,
		"hp": 18,
		"hp_max": 18,
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.5,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.75,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.5,
			Enums.DamageTypes.MELEE: 0.75,
			Enums.DamageTypes.PLASMA: 0.25,
			Enums.DamageTypes.PRISM: 0.5,
			Enums.DamageTypes.RIFLE: 0.75,
			Enums.DamageTypes.ROCKET: 0.25,
			Enums.DamageTypes.TESLA: 0.25,
		},
		"costs": {"credits": 350},
		"energy_required": 25,
		"structure_requirements":
		[
			Enums.SceneId.REMNANTS_COMMAND_CENTER,
		],
		"build_time": 10.0,
	},
	Enums.SceneId.REMNANTS_FLAME_TURRET:
	{
		"scene": "res://source/factions/the_remnants/structures/FlameTurret.tscn",
		"unit_name": "Flame Turret",
		"description": "Anti-infantry short-range turret; punishes light squads and clears growth.",
		"faction": Enums.Faction.REMNANTS,
		"production_tab_type": Enums.ProductionTabType.DEFENCES,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F3,
		"sight_range": 8.0,
		"hp": 12,
		"hp_max": 12,
		"attack_damage": 12,
		"attack_type": "explosive",
		"attack_interval": 0.6,
		"attack_range": 4.5,
		"can_attack_vines": true,
		"projectile_type": Enums.Projectile.BULLETS,
		"attack_domains": [Enums.MovementTypes.LAND],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.25,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.5,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.5,
			Enums.DamageTypes.LASER: 0.25,
			Enums.DamageTypes.MELEE: 0.5,
			Enums.DamageTypes.PLASMA: 0.1,
			Enums.DamageTypes.PRISM: 0.25,
			Enums.DamageTypes.RIFLE: 0.5,
			Enums.DamageTypes.ROCKET: 0.1,
			Enums.DamageTypes.TESLA: 0.1,
		},
		"costs": {"credits": 350},
		"energy_required": 25,
		"structure_requirements":
		[
			Enums.SceneId.REMNANTS_COMMAND_CENTER,
		],
		"build_time": 9.0,
	},
	Enums.SceneId.REMNANTS_GAUSS_TURRET:
	{
		"scene": "res://source/factions/the_remnants/structures/GaussTurret.tscn",
		"unit_name": "Gauss Turret",
		"description": "Anti-vehicle defence; high-impact armor-piercing shots.",
		"faction": Enums.Faction.REMNANTS,
		"production_tab_type": Enums.ProductionTabType.DEFENCES,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F4,
		"sight_range": 10.0,
		"hp": 14,
		"hp_max": 14,
		"attack_damage": 40,
		"attack_type": "cannon",
		"attack_interval": 1.6,
		"attack_range": 8.0,
		"can_attack_vines": true,
		"projectile_type": Enums.Projectile.CANNON,
		"attack_domains": [Enums.MovementTypes.LAND],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.5,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.5,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.5,
			Enums.DamageTypes.MELEE: 0.75,
			Enums.DamageTypes.PLASMA: 0.25,
			Enums.DamageTypes.PRISM: 0.25,
			Enums.DamageTypes.RIFLE: 0.75,
			Enums.DamageTypes.ROCKET: 0.25,
			Enums.DamageTypes.TESLA: 0.25,
		},
		"costs": {"credits": 550},
		"energy_required": 35,
		"structure_requirements":
		[
			Enums.SceneId.REMNANTS_COMMAND_CENTER,
		],
		"build_time": 12.0,
	},
	Enums.SceneId.REMNANTS_FLAK:
	{
		"scene": "res://source/factions/the_remnants/structures/Flak.tscn",
		"unit_name": "Flak",
		"description": "Anti-air defence; protects convoys and denies aircraft.",
		"faction": Enums.Faction.REMNANTS,
		"production_tab_type": Enums.ProductionTabType.DEFENCES,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F5,
		"sight_range": 10.0,
		"hp": 12,
		"hp_max": 12,
		"attack_damage": 18,
		"attack_type": "explosive",
		"attack_interval": 0.7,
		"attack_range": 8.0,
		"can_attack_vines": false,
		"projectile_type": Enums.Projectile.BULLETS,
		"attack_domains": [Enums.MovementTypes.AIR],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.25,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.5,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.25,
			Enums.DamageTypes.MELEE: 0.5,
			Enums.DamageTypes.PLASMA: 0.1,
			Enums.DamageTypes.PRISM: 0.25,
			Enums.DamageTypes.RIFLE: 0.5,
			Enums.DamageTypes.ROCKET: 0.1,
			Enums.DamageTypes.TESLA: 0.1,
		},
		"costs": {"credits": 450},
		"energy_required": 30,
		"structure_requirements":
		[
			Enums.SceneId.REMNANTS_COMMAND_CENTER,
		],
		"build_time": 10.0,
	},
	Enums.SceneId.REMNANTS_REPAIR_TURRET:
	{
		"scene": "res://source/factions/the_remnants/structures/RepairTurret.tscn",
		"unit_name": "Repair Turret",
		"description": "Utility defence; launches repair drones to nearby allies.",
		"faction": Enums.Faction.REMNANTS,
		"production_tab_type": Enums.ProductionTabType.DEFENCES,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F6,
		"sight_range": 8.0,
		"hp": 10,
		"hp_max": 10,
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.25,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.5,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.25,
			Enums.DamageTypes.MELEE: 0.5,
			Enums.DamageTypes.PLASMA: 0.1,
			Enums.DamageTypes.PRISM: 0.25,
			Enums.DamageTypes.RIFLE: 0.5,
			Enums.DamageTypes.ROCKET: 0.1,
			Enums.DamageTypes.TESLA: 0.1,
		},
		"costs": {"credits": 400},
		"energy_required": 25,
		"structure_requirements":
		[
			Enums.SceneId.REMNANTS_COMMAND_CENTER,
		],
		"build_time": 10.0,
	},
	Enums.SceneId.REMNANTS_DETECTION_TURRET:
	{
		"scene": "res://source/factions/the_remnants/structures/DetectionTurret.tscn",
		"unit_name": "Detection Turret",
		"description": "Reveals stealth, mines, burrowed threats, and hidden growth.",
		"faction": Enums.Faction.REMNANTS,
		"production_tab_type": Enums.ProductionTabType.DEFENCES,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F7,
		"sight_range": 13.0,
		"hp": 10,
		"hp_max": 10,
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.25,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.5,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.25,
			Enums.DamageTypes.MELEE: 0.5,
			Enums.DamageTypes.PLASMA: 0.1,
			Enums.DamageTypes.PRISM: 0.25,
			Enums.DamageTypes.RIFLE: 0.5,
			Enums.DamageTypes.ROCKET: 0.1,
			Enums.DamageTypes.TESLA: 0.1,
		},
		"costs": {"credits": 400},
		"energy_required": 25,
		"structure_requirements":
		[
			Enums.SceneId.REMNANTS_COMMAND_CENTER,
		],
		"build_time": 10.0,
	},
}

const INFANTRY = {
	Enums.SceneId.REMNANTS_INCINERATOR:
	{
		"scene": "res://source/factions/the_remnants/units/Incinerator.tscn",
		"unit_name": "Incinerator",
		"description": "Infantry burn-harvester that destroys vines in place.",
		"faction": Enums.Faction.REMNANTS,
		"production_tab_type": Enums.ProductionTabType.INFANTRY,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F1,
		"sight_range": 8.0,
		"hp": 80,
		"hp_max": 80,
		"resources_max": 250,
		"resources_gather_rate": 125,
		"can_move_through_vines": true,
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.0,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.0,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.0,
			Enums.DamageTypes.MELEE: 0.0,
			Enums.DamageTypes.PLASMA: 0.0,
			Enums.DamageTypes.PRISM: 0.0,
			Enums.DamageTypes.RIFLE: 0.0,
			Enums.DamageTypes.ROCKET: 0.0,
			Enums.DamageTypes.TESLA: 0.0,
		},
		"costs": {"credits": 2},
		"build_time": 3.0,
	},
	Enums.SceneId.REMNANTS_CONSTRUCTOR:
	{
		"scene": "res://source/factions/the_remnants/units/Constructor.tscn",
		"unit_name": "Constructor",
		"description": "Builds simple structures and establishes Command Posts.",
		"faction": Enums.Faction.REMNANTS,
		"production_tab_type": Enums.ProductionTabType.INFANTRY,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F2,
		"sight_range": 7.0,
		"hp": 90,
		"hp_max": 90,
		"can_move_through_vines": true,
		"movement_domains": [Enums.MovementTypes.LAND],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.0,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.0,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.0,
			Enums.DamageTypes.MELEE: 0.0,
			Enums.DamageTypes.PLASMA: 0.0,
			Enums.DamageTypes.PRISM: 0.0,
			Enums.DamageTypes.RIFLE: 0.0,
			Enums.DamageTypes.ROCKET: 0.0,
			Enums.DamageTypes.TESLA: 0.0,
		},
		"costs": {"credits": 120},
		"build_time": 10.0,
	},
	Enums.SceneId.REMNANTS_MILITIA_RIFLE_SQUAD:
	{
		"scene": "res://source/factions/the_remnants/units/MilitiaRifleSquad.tscn",
		"unit_name": "Militia Rifle Squad",
		"description": "Cheap core DPS infantry for civilian defence and light-threat clearing.",
		"faction": Enums.Faction.REMNANTS,
		"production_tab_type": Enums.ProductionTabType.INFANTRY,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F3,
		"sight_range": 7.0,
		"hp": 110,
		"hp_max": 110,
		"can_move_through_vines": true,
		"attack_damage": 9,
		"attack_type": "rifle",
		"attack_interval": 0.5,
		"attack_range": 5.5,
		"can_attack_vines": true,
		"projectile_type": Enums.Projectile.BULLETS,
		"attack_domains": [Enums.MovementTypes.LAND],
		"movement_domains": [Enums.MovementTypes.LAND],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.0,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.0,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.0,
			Enums.DamageTypes.MELEE: 0.0,
			Enums.DamageTypes.PLASMA: 0.0,
			Enums.DamageTypes.PRISM: 0.0,
			Enums.DamageTypes.RIFLE: 0.0,
			Enums.DamageTypes.ROCKET: 0.0,
			Enums.DamageTypes.TESLA: 0.0,
		},
		"costs": {"credits": 130},
		"build_time": 10.0,
	},
	Enums.SceneId.REMNANTS_ROCKET_TEAM:
	{
		"scene": "res://source/factions/the_remnants/units/RocketTeam.tscn",
		"unit_name": "Rocket Team",
		"description": "Anti-armor and basic anti-air infantry.",
		"faction": Enums.Faction.REMNANTS,
		"production_tab_type": Enums.ProductionTabType.INFANTRY,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F4,
		"sight_range": 8.0,
		"hp": 100,
		"hp_max": 100,
		"can_move_through_vines": true,
		"attack_damage": 28,
		"attack_type": "rocket",
		"attack_interval": 1.8,
		"attack_range": 6.0,
		"projectile_type": Enums.Projectile.ROCKET,
		"attack_domains": [Enums.MovementTypes.LAND, Enums.MovementTypes.AIR],
		"movement_domains": [Enums.MovementTypes.LAND],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.0,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.0,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.0,
			Enums.DamageTypes.MELEE: 0.0,
			Enums.DamageTypes.PLASMA: 0.0,
			Enums.DamageTypes.PRISM: 0.0,
			Enums.DamageTypes.RIFLE: 0.0,
			Enums.DamageTypes.ROCKET: 0.0,
			Enums.DamageTypes.TESLA: 0.0,
		},
		"costs": {"credits": 200},
		"build_time": 13.0,
	},
	Enums.SceneId.REMNANTS_SNIPER:
	{
		"scene": "res://source/factions/the_remnants/units/Sniper.tscn",
		"unit_name": "Sniper",
		"description": "Long-range precision infantry; high-value target removal.",
		"faction": Enums.Faction.REMNANTS,
		"production_tab_type": Enums.ProductionTabType.INFANTRY,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F5,
		"sight_range": 12.0,
		"hp": 80,
		"hp_max": 80,
		"can_move_through_vines": true,
		"attack_damage": 60,
		"attack_type": "rifle",
		"attack_interval": 2.5,
		"attack_range": 11.0,
		"projectile_type": Enums.Projectile.BULLETS,
		"attack_domains": [Enums.MovementTypes.LAND],
		"movement_domains": [Enums.MovementTypes.LAND],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.0,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.0,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.0,
			Enums.DamageTypes.MELEE: 0.0,
			Enums.DamageTypes.PLASMA: 0.0,
			Enums.DamageTypes.PRISM: 0.0,
			Enums.DamageTypes.RIFLE: 0.0,
			Enums.DamageTypes.ROCKET: 0.0,
			Enums.DamageTypes.TESLA: 0.0,
		},
		"costs": {"credits": 220},
		"build_time": 14.0,
	},
	Enums.SceneId.REMNANTS_CHEMICAL_TEAM:
	{
		"scene": "res://source/factions/the_remnants/units/ChemicalTeam.tscn",
		"unit_name": "Chemical Team",
		"description": "Chemical area-denial and anti-infantry pressure.",
		"faction": Enums.Faction.REMNANTS,
		"production_tab_type": Enums.ProductionTabType.INFANTRY,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F6,
		"sight_range": 7.0,
		"hp": 100,
		"hp_max": 100,
		"can_move_through_vines": true,
		"attack_damage": 18,
		"attack_type": "corrosive",
		"attack_interval": 1.4,
		"attack_range": 5.0,
		"can_attack_vines": true,
		"projectile_type": Enums.Projectile.BULLETS,
		"attack_domains": [Enums.MovementTypes.LAND],
		"movement_domains": [Enums.MovementTypes.LAND],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.0,
			Enums.DamageTypes.CORROSIVE: 0.5,
			Enums.DamageTypes.CRUSH: 0.0,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.25,
			Enums.DamageTypes.LASER: 0.0,
			Enums.DamageTypes.MELEE: 0.0,
			Enums.DamageTypes.PLASMA: 0.0,
			Enums.DamageTypes.PRISM: 0.0,
			Enums.DamageTypes.RIFLE: 0.0,
			Enums.DamageTypes.ROCKET: 0.0,
			Enums.DamageTypes.TESLA: 0.0,
		},
		"costs": {"credits": 200},
		"build_time": 13.0,
	},
	Enums.SceneId.REMNANTS_MECHANIC:
	{
		"scene": "res://source/factions/the_remnants/units/Mechanic.tscn",
		"unit_name": "Mechanic",
		"description": "Repairs allies, places mines, supports convoys.",
		"faction": Enums.Faction.REMNANTS,
		"production_tab_type": Enums.ProductionTabType.INFANTRY,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F7,
		"sight_range": 7.0,
		"hp": 90,
		"hp_max": 90,
		"can_move_through_vines": true,
		"movement_domains": [Enums.MovementTypes.LAND],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.0,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.0,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.0,
			Enums.DamageTypes.MELEE: 0.0,
			Enums.DamageTypes.PLASMA: 0.0,
			Enums.DamageTypes.PRISM: 0.0,
			Enums.DamageTypes.RIFLE: 0.0,
			Enums.DamageTypes.ROCKET: 0.0,
			Enums.DamageTypes.TESLA: 0.0,
		},
		"costs": {"credits": 180},
		"build_time": 12.0,
	},
	Enums.SceneId.REMNANTS_COMMANDER:
	{
		"scene": "res://source/factions/the_remnants/units/Commander.tscn",
		"unit_name": "Commander",
		"description": "Buffs nearby units with damage and speed; non-stacking aura.",
		"faction": Enums.Faction.REMNANTS,
		"production_tab_type": Enums.ProductionTabType.INFANTRY,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F8,
		"sight_range": 9.0,
		"hp": 160,
		"hp_max": 160,
		"can_move_through_vines": true,
		"attack_damage": 12,
		"attack_type": "rifle",
		"attack_interval": 0.7,
		"attack_range": 5.0,
		"projectile_type": Enums.Projectile.BULLETS,
		"attack_domains": [Enums.MovementTypes.LAND],
		"movement_domains": [Enums.MovementTypes.LAND],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.25,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.25,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.25,
			Enums.DamageTypes.MELEE: 0.5,
			Enums.DamageTypes.PLASMA: 0.1,
			Enums.DamageTypes.PRISM: 0.1,
			Enums.DamageTypes.RIFLE: 0.5,
			Enums.DamageTypes.ROCKET: 0.1,
			Enums.DamageTypes.TESLA: 0.1,
		},
		"costs": {"credits": 350},
		"build_time": 18.0,
	},
}

const VEHICLES = {
	Enums.SceneId.REMNANTS_FLAME_TANK:
	{
		"scene": "res://source/factions/the_remnants/units/FlameTank.tscn",
		"unit_name": "Flame Tank",
		"description": "Vehicle burn-harvester that destroys vines in place.",
		"faction": Enums.Faction.REMNANTS,
		"production_tab_type": Enums.ProductionTabType.VEHICLE,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F1,
		"sight_range": 8.0,
		"hp": 1000,
		"hp_max": 1000,
		"resources_max": 500,
		"resources_gather_rate": 250,
		"can_move_through_vines": true,
		"can_reverse_move": true,
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.5,
			Enums.DamageTypes.CORROSIVE: 0.5,
			Enums.DamageTypes.CRUSH: 0.5,
			Enums.DamageTypes.EXPLOSIVE: 0.5,
			Enums.DamageTypes.FIRE: 0.5,
			Enums.DamageTypes.LASER: 0.5,
			Enums.DamageTypes.MELEE: 0.5,
			Enums.DamageTypes.PLASMA: 0.5,
			Enums.DamageTypes.PRISM: 0.5,
			Enums.DamageTypes.RIFLE: 0.5,
			Enums.DamageTypes.ROCKET: 0.5,
			Enums.DamageTypes.TESLA: 0.5,
		},
		"costs": {"credits": 3},
		"build_time": 6.0,
	},
	Enums.SceneId.REMNANTS_SCOUT_BIKE:
	{
		"scene": "res://source/factions/the_remnants/units/ScoutBike.tscn",
		"unit_name": "Scout Bike",
		"description": "Fast scout and harasser; map control vehicle.",
		"faction": Enums.Faction.REMNANTS,
		"production_tab_type": Enums.ProductionTabType.VEHICLE,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F2,
		"sight_range": 11.0,
		"hp": 180,
		"hp_max": 180,
		"attack_damage": 8,
		"attack_type": "rifle",
		"attack_interval": 0.4,
		"attack_range": 5.0,
		"can_attack_vines": true,
		"projectile_type": Enums.Projectile.BULLETS,
		"attack_domains": [Enums.MovementTypes.LAND],
		"movement_domains": [Enums.MovementTypes.LAND],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.0,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.0,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.0,
			Enums.DamageTypes.MELEE: 0.0,
			Enums.DamageTypes.PLASMA: 0.0,
			Enums.DamageTypes.PRISM: 0.0,
			Enums.DamageTypes.RIFLE: 0.0,
			Enums.DamageTypes.ROCKET: 0.0,
			Enums.DamageTypes.TESLA: 0.0,
		},
		"costs": {"credits": 200},
		"build_time": 10.0,
	},
	Enums.SceneId.REMNANTS_SALVAGE_VAN:
	{
		"scene": "res://source/factions/the_remnants/units/SalvageVan.tscn",
		"unit_name": "Salvage Van",
		"description": "Gathers scrap dropped by destroyed enemy vehicles and air units.",
		"faction": Enums.Faction.REMNANTS,
		"production_tab_type": Enums.ProductionTabType.VEHICLE,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F3,
		"sight_range": 8.0,
		"hp": 280,
		"hp_max": 280,
		"movement_domains": [Enums.MovementTypes.LAND],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.25,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.25,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.25,
			Enums.DamageTypes.MELEE: 0.25,
			Enums.DamageTypes.PLASMA: 0.1,
			Enums.DamageTypes.PRISM: 0.1,
			Enums.DamageTypes.RIFLE: 0.25,
			Enums.DamageTypes.ROCKET: 0.1,
			Enums.DamageTypes.TESLA: 0.1,
		},
		"costs": {"credits": 300},
		"build_time": 14.0,
	},
	Enums.SceneId.REMNANTS_BREAKER_TANK:
	{
		"scene": "res://source/factions/the_remnants/units/BreakerTank.tscn",
		"unit_name": "Breaker Tank",
		"description": "Durable anchor; anti-armor and boss-fight tank.",
		"faction": Enums.Faction.REMNANTS,
		"production_tab_type": Enums.ProductionTabType.VEHICLE,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F4,
		"sight_range": 8.0,
		"hp": 520,
		"hp_max": 520,
		"attack_damage": 38,
		"attack_type": "cannon",
		"attack_interval": 1.6,
		"attack_range": 6.0,
		"can_attack_vines": true,
		"projectile_type": Enums.Projectile.CANNON,
		"attack_domains": [Enums.MovementTypes.LAND],
		"movement_domains": [Enums.MovementTypes.LAND],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.5,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.5,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.5,
			Enums.DamageTypes.MELEE: 0.5,
			Enums.DamageTypes.PLASMA: 0.25,
			Enums.DamageTypes.PRISM: 0.25,
			Enums.DamageTypes.RIFLE: 0.5,
			Enums.DamageTypes.ROCKET: 0.25,
			Enums.DamageTypes.TESLA: 0.25,
		},
		"costs": {"credits": 380},
		"build_time": 18.0,
	},
	Enums.SceneId.REMNANTS_FIRING_PORT_APC:
	{
		"scene": "res://source/factions/the_remnants/units/FiringPortAPC.tscn",
		"unit_name": "Firing-Port APC",
		"description": "Transports infantry; passengers can shoot out.",
		"faction": Enums.Faction.REMNANTS,
		"production_tab_type": Enums.ProductionTabType.VEHICLE,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F5,
		"sight_range": 7.0,
		"hp": 360,
		"hp_max": 360,
		"movement_domains": [Enums.MovementTypes.LAND],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.25,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.25,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.25,
			Enums.DamageTypes.MELEE: 0.5,
			Enums.DamageTypes.PLASMA: 0.1,
			Enums.DamageTypes.PRISM: 0.1,
			Enums.DamageTypes.RIFLE: 0.5,
			Enums.DamageTypes.ROCKET: 0.1,
			Enums.DamageTypes.TESLA: 0.1,
		},
		"costs": {"credits": 300},
		"build_time": 14.0,
	},
	Enums.SceneId.REMNANTS_MORTAR_TRUCK:
	{
		"scene": "res://source/factions/the_remnants/units/MortarTruck.tscn",
		"unit_name": "Mortar Truck",
		"description": "Siege vs static defences and shrine camps.",
		"faction": Enums.Faction.REMNANTS,
		"production_tab_type": Enums.ProductionTabType.VEHICLE,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F6,
		"sight_range": 8.0,
		"hp": 280,
		"hp_max": 280,
		"attack_damage": 50,
		"attack_type": "explosive",
		"attack_interval": 2.4,
		"attack_range": 9.0,
		"can_attack_vines": true,
		"projectile_type": Enums.Projectile.ROCKET,
		"attack_domains": [Enums.MovementTypes.LAND],
		"movement_domains": [Enums.MovementTypes.LAND],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.25,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.25,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.25,
			Enums.DamageTypes.MELEE: 0.25,
			Enums.DamageTypes.PLASMA: 0.1,
			Enums.DamageTypes.PRISM: 0.1,
			Enums.DamageTypes.RIFLE: 0.25,
			Enums.DamageTypes.ROCKET: 0.1,
			Enums.DamageTypes.TESLA: 0.1,
		},
		"costs": {"credits": 500},
		"build_time": 18.0,
	},
	Enums.SceneId.REMNANTS_SCRAP_WALKER:
	{
		"scene": "res://source/factions/the_remnants/units/ScrapWalker.tscn",
		"unit_name": "Scrap Walker",
		"description": "Heavy anti-air and anti-ground fire support walker.",
		"faction": Enums.Faction.REMNANTS,
		"production_tab_type": Enums.ProductionTabType.VEHICLE,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F7,
		"sight_range": 10.0,
		"hp": 700,
		"hp_max": 700,
		"attack_damage": 24,
		"attack_type": "explosive",
		"attack_interval": 0.8,
		"attack_range": 7.0,
		"can_attack_vines": true,
		"projectile_type": Enums.Projectile.BULLETS,
		"attack_domains": [Enums.MovementTypes.LAND, Enums.MovementTypes.AIR],
		"movement_domains": [Enums.MovementTypes.LAND],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.5,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.5,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.5,
			Enums.DamageTypes.MELEE: 0.5,
			Enums.DamageTypes.PLASMA: 0.25,
			Enums.DamageTypes.PRISM: 0.25,
			Enums.DamageTypes.RIFLE: 0.5,
			Enums.DamageTypes.ROCKET: 0.25,
			Enums.DamageTypes.TESLA: 0.25,
		},
		"costs": {"credits": 800},
		"build_time": 26.0,
	},
	Enums.SceneId.REMNANTS_GAUSS_ARTILLERY:
	{
		"scene": "res://source/factions/the_remnants/units/GaussArtillery.tscn",
		"unit_name": "Gauss Artillery",
		"description": "Anti-turtle finisher; long-warning siege gun.",
		"faction": Enums.Faction.REMNANTS,
		"production_tab_type": Enums.ProductionTabType.VEHICLE,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F8,
		"sight_range": 9.0,
		"hp": 360,
		"hp_max": 360,
		"attack_damage": 90,
		"attack_type": "cannon",
		"attack_interval": 3.5,
		"attack_range": 12.0,
		"can_attack_vines": true,
		"projectile_type": Enums.Projectile.CANNON,
		"attack_domains": [Enums.MovementTypes.LAND],
		"movement_domains": [Enums.MovementTypes.LAND],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.25,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.25,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.25,
			Enums.DamageTypes.MELEE: 0.25,
			Enums.DamageTypes.PLASMA: 0.1,
			Enums.DamageTypes.PRISM: 0.1,
			Enums.DamageTypes.RIFLE: 0.25,
			Enums.DamageTypes.ROCKET: 0.1,
			Enums.DamageTypes.TESLA: 0.1,
		},
		"costs": {"credits": 700},
		"build_time": 24.0,
	},
}

const AIR = {
	Enums.SceneId.REMNANTS_RECON_DRONE:
	{
		"scene": "res://source/factions/the_remnants/units/ReconDrone.tscn",
		"unit_name": "Recon Drone",
		"description": "Vision and detection scout drone; no real weapon.",
		"faction": Enums.Faction.REMNANTS,
		"production_tab_type": Enums.ProductionTabType.AIR,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F1,
		"sight_range": 14.0,
		"hp": 120,
		"hp_max": 120,
		"movement_domains": [Enums.MovementTypes.AIR],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.0,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.0,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.0,
			Enums.DamageTypes.MELEE: 0.0,
			Enums.DamageTypes.PLASMA: 0.0,
			Enums.DamageTypes.PRISM: 0.0,
			Enums.DamageTypes.RIFLE: 0.0,
			Enums.DamageTypes.ROCKET: 0.0,
			Enums.DamageTypes.TESLA: 0.0,
		},
		"costs": {"credits": 200},
		"build_time": 10.0,
	},
	Enums.SceneId.REMNANTS_GUN_DRONE:
	{
		"scene": "res://source/factions/the_remnants/units/GunDrone.tscn",
		"unit_name": "Gun Drone",
		"description": "Light air harasser; convoy cover and pursuit.",
		"faction": Enums.Faction.REMNANTS,
		"production_tab_type": Enums.ProductionTabType.AIR,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F2,
		"sight_range": 9.0,
		"hp": 220,
		"hp_max": 220,
		"movement_domains": [Enums.MovementTypes.AIR],
		"attack_damage": 10,
		"attack_type": "rifle",
		"attack_interval": 0.4,
		"attack_range": 5.0,
		"projectile_type": Enums.Projectile.BULLETS,
		"attack_domains": [Enums.MovementTypes.LAND, Enums.MovementTypes.AIR],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.0,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.0,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.0,
			Enums.DamageTypes.MELEE: 0.0,
			Enums.DamageTypes.PLASMA: 0.0,
			Enums.DamageTypes.PRISM: 0.0,
			Enums.DamageTypes.RIFLE: 0.0,
			Enums.DamageTypes.ROCKET: 0.0,
			Enums.DamageTypes.TESLA: 0.0,
		},
		"costs": {"credits": 280},
		"build_time": 13.0,
	},
	Enums.SceneId.REMNANTS_SUICIDE_DRONE:
	{
		"scene": "res://source/factions/the_remnants/units/SuicideDrone.tscn",
		"unit_name": "Suicide Drone",
		"description": "Cheap telegraphed explosive drone; AoE detonation on impact.",
		"faction": Enums.Faction.REMNANTS,
		"production_tab_type": Enums.ProductionTabType.AIR,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F3,
		"sight_range": 8.0,
		"hp": 80,
		"hp_max": 80,
		"movement_domains": [Enums.MovementTypes.AIR],
		"attack_damage": 80,
		"attack_type": "explosive",
		"attack_interval": 5.0,
		"attack_range": 1.5,
		"can_attack_vines": true,
		"projectile_type": Enums.Projectile.BULLETS,
		"attack_domains": [Enums.MovementTypes.LAND, Enums.MovementTypes.AIR],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.0,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.0,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.0,
			Enums.DamageTypes.MELEE: 0.0,
			Enums.DamageTypes.PLASMA: 0.0,
			Enums.DamageTypes.PRISM: 0.0,
			Enums.DamageTypes.RIFLE: 0.0,
			Enums.DamageTypes.ROCKET: 0.0,
			Enums.DamageTypes.TESLA: 0.0,
		},
		"costs": {"credits": 150},
		"build_time": 8.0,
	},
	Enums.SceneId.REMNANTS_HEAVY_LIFT_ROTOR:
	{
		"scene": "res://source/factions/the_remnants/units/HeavyLiftRotor.tscn",
		"unit_name": "Heavy Lift Rotor",
		"description": "Late transport, extraction, and vehicle deployment.",
		"faction": Enums.Faction.REMNANTS,
		"production_tab_type": Enums.ProductionTabType.AIR,
		"production_tab_grid_slot": Enums.ProductionTabGridSlots.F4,
		"sight_range": 9.0,
		"hp": 500,
		"hp_max": 500,
		"movement_domains": [Enums.MovementTypes.AIR],
		"armor":
		{
			Enums.DamageTypes.CANNON: 0.25,
			Enums.DamageTypes.CORROSIVE: 0.0,
			Enums.DamageTypes.CRUSH: 0.25,
			Enums.DamageTypes.EXPLOSIVE: 0.0,
			Enums.DamageTypes.FIRE: 0.0,
			Enums.DamageTypes.LASER: 0.25,
			Enums.DamageTypes.MELEE: 0.25,
			Enums.DamageTypes.PLASMA: 0.1,
			Enums.DamageTypes.PRISM: 0.1,
			Enums.DamageTypes.RIFLE: 0.25,
			Enums.DamageTypes.ROCKET: 0.1,
			Enums.DamageTypes.TESLA: 0.1,
		},
		"costs": {"credits": 450},
		"build_time": 18.0,
	},
}

const NAVY = {}
